### ISSUE TITLE
[BUG] Carthief ReadMe is wrong

### ISSUE THREAD

**Issue by 69edgy420me** [DiscworldZA/gta-resources#1]
The description for this [page](https://github.com/DiscworldZA/gta-resources/tree/master/disc-carthief) is the description of drugs when it should be the carthief description.

**Comment by DiscworldZA** [comment]
Hi

Thanks for catching this! Happens when you copy and paste! Will fix it

**Comment by DiscworldZA** [comment]
updated the readme for carthief to contain the car thief usage information
