### ISSUE TITLE
[BUG] - inventoryhud

### ISSUE THREAD

**Issue by teryusanru** [DiscworldZA/gta-resources#100]
i don't know its bug or what. but if you setup the rewards in your script like 2 item or more for the reward it not appear in your inventory hud and the database. i solve that using /ensureinv but the management of slot is sort by itself. hope you auto sync the database from the default inventory of es_extended. good work for the inventory. thanks

**Comment by Duqino** [comment]
Are you giving the players real items like water or bread? Because you need to use real items or it wont work. ensureinv is only for syncing both inventorty scripts (esx and disc inventoryhud)

**Comment by teryusanru** [comment]
yap i have real item for my database. yap i get it. the issue is can you make the ensure not re-sort the slot item? hope this help. oh and you can spam for give item, i get possibilities for not getting the item. no error in my rcon and my console ingame. just a little bit to go smoother.

**Comment by BechaRoot** [comment]
are u fix it @teryusanru ?

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
