### ISSUE TITLE
[BUG] Inventoryhud 

### ISSUE THREAD

**Issue by billyfriend2018** [DiscworldZA/gta-resources#106]
So when you use a items it does not remove the item from your inventory. I have the newest Inventoryhud installed

**Comment by teryusanru** [comment]
have you see in the database in the table items you can edit canremove to 1 for each item.

**Comment by DiscworldZA** [comment]
Does the item get removed from your ESX inventory?

**Comment by billyfriend2018** [comment]
yes @DiscworldZA but when i use the item it does not remove

**Comment by DiscworldZA** [comment]
I have put a fix in for this lastnight. Please use the newest update and let me know if it still happens
