### ISSUE TITLE
Auto Remove Weapon Bug [BUG]

### ISSUE THREAD

**Issue by mamadlooloo** [DiscworldZA/gta-resources#108]
Hello
I have a problem with weapons.
For Example:
I have two weapon in my inventory (weapon 1 in slot 2 AND weapon 2 in slot 7).
I'm press TAB and i can see slot 2 with weapon , no problem.
I'm press Number 2 for using weapon 1 , my weapon pull out with no problem.
Weapon 1 in my hand and i press F2 to open inventory.
I remove weapon from slot 7 to DROP section AND weapon 1 disappear from inventory.
I test this bug in trunk instead DROP section and still work this bug in trunk.
--------------------------------------------
[(
No matter which weapon you use in slot 2 and 7.
Same weapon or different weapon, no matter.
 )]
--------------------------------------------
Another thing is i add silencer to my PISTOL and when i grab in to my pocket and again pullout , silencer remove from PISTOL.

**Comment by DiscworldZA** [comment]
Can you please provide video evidence?
