### ISSUE TITLE
[BUG] Same inventory on other character [Disc-Inventoryhud]

### ISSUE THREAD

**Issue by Stickarn** [DiscworldZA/gta-resources#113]
When using esx_kashacters and using mutiple characters. Every one has the same inventory.. Is there a way to fix so it just pulls for that character or will i have to wait for your own character system?

**Comment by iTzCrutchie** [comment]
Add the table to the server script of kashacters like everything else.

**Comment by EquippedPig** [comment]
What table would that be?

**Comment by Stickarn** [comment]
i did {table = "disc_inventory", column = "owner"}, and it seemed to work

**Comment by EquippedPig** [comment]
Okay sounds good, where at in the server script of kash?

**Comment by SW1FT** [comment]
server/main.lua inside IdentifierTables
