### ISSUE TITLE
[BUG]item inventory

### ISSUE THREAD

**Issue by merder123** [DiscworldZA/gta-resources#118]
i craft item marijurna use cannabis but item in disc-inventory remain the same

item in disc-inventory sql 
![1](https://user-images.githubusercontent.com/21078519/67392179-4917b480-f5ca-11e9-9a89-c1d27784cecb.PNG)

item in user_inventory esx sql 
![2](https://user-images.githubusercontent.com/21078519/67392190-4ddc6880-f5ca-11e9-843b-02a77ff246c6.PNG)

item in game
![3](https://user-images.githubusercontent.com/21078519/67392196-4fa62c00-f5ca-11e9-96ac-67cb3b77be83.PNG)

**Comment by merder123** [comment]
help

**Comment by rex2630** [comment]
Did u fixed it?What is your config?

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
