### ISSUE TITLE
[BUG] Buying from store when you have no money.

### ISSUE THREAD

**Issue by stianhje** [DiscworldZA/gta-resources#119]
**Describe the bug**
After you fixed the dupe bug yesterday with adding the UnlockInventory() and LockInventory() in the inventory.js this bug appeared. Inventory locks itself and you have to use ensureInv to fix it.
No errors in client or server console.

Just ignore the layout of the inventory, i am using the latest version.

**To Reproduce**
1. Buy from a store without having enough cash.

**Expected behavior**
Get an error message where you get a notification that you dont have enough money to buy that item? And not have the inventory lock itself.

**Videos**
https://gyazo.com/5277a81d5bd69e579a310726e39beb11

Absolutly love your work man!

**Comment by DocBurN** [comment]
happened to me, 100% replicable, have to restart to unlock

**Comment by DiscworldZA** [comment]
Fixed. Should unlock properly now
