### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rhoy1871** [DiscworldZA/gta-resources#122]
1. I got this error when i giving item to other players.
![error](https://user-images.githubusercontent.com/40468854/67456046-76318a80-f5fd-11e9-9db0-43c8981ef5b8.png)

**Comment by rex2630** [comment]
Was this fixed with https://github.com/DiscworldZA/gta-resources/commit/6d4989e06fae3711cf101ac772901cae3eb74628 and https://github.com/DiscworldZA/gta-resources/commit/922e63f531c7a8a7c0472616ee861f34b54ce6f8 ? Please update inventory

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
