### ISSUE TITLE
[BUG] Not able to give items or cash

### ISSUE THREAD

**Issue by KoolAiddTV** [DiscworldZA/gta-resources#135]
**Describe the bug**
I can't give anyone cash or items on my build

**To Reproduce**
1. Go to the inventory menu
2. Click on Pay
3. Choose player
4. Getting the response "Giving 5(amount) undefined to Nearby Player with Server ID"

**Screenshots**
http://prntscr.com/pobhpd

**Comment by TheBritishBrotherhood** [comment]
Are you using the latest update?

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
