### ISSUE TITLE
its impossible to reload the appistol (I can load ammo in a regular pistol). Tried 5 type of ammo on it (with the appistol in my hand)

### ISSUE THREAD

**Issue by DocBurN** [DiscworldZA/gta-resources#137]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Videos**
If applicable, add videos to help explain your problem.

**Additional context**

**Comment by TeamFishbowl** [comment]
disc-ammo/config.lua , Just add AP pistol in here and it should work ?

    {
        name = 'disc_ammo_pistol_large',
        weapons = {
            `WEAPON_PISTOL`,
			`WEAPON_SNSPISTOL`,
            `WEAPON_COMBATPISTOL`,
            `WEAPON_HEAVYPISTOL`,
            `WEAPON_MACHINEPISTOL`,
            `WEAPON_MARKSMANPISTOL`,
            `WEAPON_PISTOL50`,
            `WEAPON_VINTAGEPISTOL`
        },
        count = 60
    },

**Comment by DocBurN** [comment]
oh god the shame, sorry for wasting your time, i'll try tonight but its seem quite logical.. i was too busy working on other luas to even check inside the config.. since it was working on other pistol naturally without tweaking.. thank you!

**Comment by TeamFishbowl** [comment]
no problem let me know if it works as i haven't tried it yet but just spotted that stuff in the config last night haha

**Comment by DocBurN** [comment]
just to confirm its working flawlessly when the config reflects reality.. added the appistol to the list and it work. my bad.. love the script.. i thought i was doing a good deed spoting bug but its user error.
