### ISSUE TITLE
[BUG] Swapping stack with the same item type causing UI to break

### ISSUE THREAD

**Issue by DoctorTwitch** [DiscworldZA/gta-resources#139]
**Describe the bug**
Swapping stacks with the same item type causing UI to break

**To Reproduce**
1. Hit F2 to open the inventory
2. Using bread as an example. Have 1 full stack, and 1 about half stack
3. Click on the full stack bread, and swap it to the half stack

**Expected behavior**
The UI break, because the item count is over the stack limit. And require a script restart or /ensureInv to disable the black screen 

**Screenshots**
https://i.imgur.com/xVchxNM.jpg

**Videos**
https://streamable.com/6qh8x

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
