### ISSUE TITLE
Weapon use in Vehicle

### ISSUE THREAD

**Issue by mamadlooloo** [DiscworldZA/gta-resources#141]
Hello
When i driving in vehicle can't using any weapon.
Please fix it.
[ THANKS ]

**Comment by TeamFishbowl** [comment]
i know this is 4 days old but you can use guns in car with this hud at least i never had issues doing it, of course only pistols will work though.

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
