### ISSUE TITLE
[BUG] Disc-Inventoryhud - Unable to take/use 2 items correctly

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [DiscworldZA/gta-resources#143]
**Describe the bug**
If you use 2 items at the extact same time, Only one of the items removes itself from the inventory view. Same with if you job requires to use 2 items at once the inventory still shows one of the items.

**To Reproduce**
1. Buy 2 items (for this we will use food.
2. Put one item in slot 1 and one items in slot 2
3. Press 1 & 2 together at the same time
4. See issue (only one removes itself (the DB updates correctly)

**Expected behavior**
For it to take both items.

**Additional context**
Im assuming the inventory has no handle of if 2 items are used at once, This for sure needs to be fixed as for myself its a game breaker as some of my activities take/use 2 items at once.

**Comment by TheBritishBrotherhood** [comment]
Feature also -

Add gun licence checks to a weapon store.

Config to enable and disable.

<3

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
