### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xaph1k** [DiscworldZA/gta-resources#144]
You're able to store cars that you haven't bought into ur garage, for disc-property

**Comment by drnick7000** [comment]
There is an option in the config to make it owned vehicles only which worked for me fine.

**Comment by rex2630** [comment]
U can change it in config here: https://github.com/DiscworldZA/gta-resources/blob/master/disc-property/config.lua#L9 I hope this helped. Im closing this since it isnt a issue
