### ISSUE TITLE
[BUG] duping items

### ISSUE THREAD

**Issue by Cmoen11** [DiscworldZA/gta-resources#148]
**Describe the bug**

**To Reproduce**
steps:
1. throw an item. 
2. Two people go view the item
3. both clicks on the item and hower its own inventory
4. both clicks its own inventory with the new item selected.
actual: Both retrieves the item

Suggested solution is to prevent people from watching drops like these at the same time..
**Expected behavior**

Both get the item in their inventory

**Comment by rex2630** [comment]
This was already fixed with this commit: https://github.com/DiscworldZA/gta-resources/commit/755de2ae316e324eb77db29dfb017410f0605b9f . Please close the issue

**Comment by rex2630** [comment]
Please update inventoryhud to newest version, its already fixed in there. Thanks for your report :)
