### ISSUE TITLE
[BUG] Bug?? Fivem update

### ISSUE THREAD

**Issue by Duqino** [DiscworldZA/gta-resources#152]
I got this after latest fivem server update:

[![Screenshot from Gyazo](https://gyazo.com/8ea2b4a32ed8286b9f72647038513d3d/raw)](https://gyazo.com/8ea2b4a32ed8286b9f72647038513d3d)
[![Screenshot from Gyazo](https://gyazo.com/62263800ab1f7ab8a58ba678455eccac/raw)](https://gyazo.com/62263800ab1f7ab8a58ba678455eccac)

**Comment by DiscworldZA** [comment]
This is not from inventoryhud

**Comment by Duqino** [comment]
Oke it happend after updating inv hud.
