### ISSUE TITLE
can't give the item [BUG]

### ISSUE THREAD

**Issue by TGIANN** [DiscworldZA/gta-resources#153]
i can't give the item

**Screenshots**
![Adsız1](https://user-images.githubusercontent.com/54374780/68076101-b0e7af80-fdc1-11e9-99c6-b5f3e4b6e270.png)
![Screenshot_1](https://user-images.githubusercontent.com/54374780/68076102-b1804600-fdc1-11e9-9ed5-8ec202697e5f.png)

**Comment by rex2630** [comment]
Is still issue happening on newest version?

**Comment by rex2630** [comment]
Please update the inventoryhud. It has been fixed in newest update. Thanks for report :)
