### ISSUE TITLE
[BUG] Disc-inventoryHUD and Ambulancejob

### ISSUE THREAD

**Issue by Revel1990** [DiscworldZA/gta-resources#154]
**Describe the bug**
When you die and respawn the items will be deleted. on the background it's deleted but you still have it and the items are unable to use. i use this with ambulancejob

**To Reproduce**
1. You die and click on respawn. when respawned you still have the items in your inventory. but they all dont work
2. try using WEAPON_PISTOL or water. none of them work after respawn at hospital.

**Expected behavior**
Delete all items after respawn at hospital. maybe the fix is in ambulancejob, if so i gonna make a request for making Disc-EMSjob

**Extra info**
Keep up the goodwork!

**Comment by TGIANN** [comment]
esx_ambulancejob/server/server.lua

> find 
> `xPlayer.removeWeapon(xPlayer.loadout[i].name)`
> 
> Replace
> `xPlayer.removeInventoryItem(xPlayer.loadout[i].name)`

> find
> `xPlayer.addWeapon(playerLoadout[i].name, playerLoadout[i].ammo)`
> 
> replace
> `xPlayer.addInventoryItem(playerLoadout[i].name,1)`

**Comment by Revel1990** [comment]
Thanks for the quick reply!

I believe it worked. but i get a black screen after i respawn. i can do a revive in F8 and do revive

**Comment by Revel1990** [comment]
![image](https://user-images.githubusercontent.com/23440918/68091984-c246bf80-fe86-11e9-82d3-985aa8e56314.png)

this is what is get

**Comment by TGIANN** [comment]
ambuncejob/server/main.lua
find

> xPlayer.removeInventoryItem(xPlayer.loadout[i].name)

replace
> xPlayer.removeInventoryItem(xPlayer.loadout[i].name, 1)

**Comment by Revel1990** [comment]
`	local playerLoadout = {}
	if Config.RemoveWeaponsAfterRPDeath then
		for i=1, #xPlayer.loadout, 1 do
--			xPlayer.removeWeapon(xPlayer.loadout[i].name)
			xPlayer.removeInventoryItem(xPlayer.loadout[i].name, 1)
		end
	else -- save weapons & restore em' since spawnmanager removes them
		for i=1, #xPlayer.loadout, 1 do
			table.insert(playerLoadout, xPlayer.loadout[i])
		end

		-- give back wepaons after a couple of seconds
		Citizen.CreateThread(function()
			Citizen.Wait(5000)
			for i=1, #playerLoadout, 1 do
				if playerLoadout[i].label ~= nil then
					xPlayer.addInventoryItem(playerLoadout[i].name,1)
--					xPlayer.addWeapon(playerLoadout[i].name, playerLoadout[i].ammo)
				end
			end
		end)
	end`

ok with /ensureInv i got a clean inventoryhud.

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
