### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by axus2** [DiscworldZA/gta-resources#157]
Good, I comment I am apparently having an error in the inventory or I am doing something wrong, when I give myself articles if I get the normal one but when giving me weapons it does not appear in my inventory, here I leave you the video and some photos of the errors that I gives

https://www.twitch.tv/videos/505053412 (problem recording)

![Screenshot_11](https://user-images.githubusercontent.com/55525450/68383104-c5b2a300-0133-11ea-828f-a96a9b41ce02.png)

server side line error 580

  function handleWeaponRemoval(data, source)
    if isWeapon(data.originItem.id) then
        if data.originOwner == data.destinationOwner and data.originTier.name == data.destinationTier.name then
            if data.destinationSlot > 5 then
                TriggerClientEvent('disc-inventoryhud:removeCurrentWeapon', source)
            end
        else
            TriggerClientEvent('disc-inventoryhud:removeCurrentWeapon', source)
        end
    end
end

--------

server side line error 35

RegisterServerEvent("disc-inventoryhud:MoveToEmpty")
AddEventHandler("disc-inventoryhud:MoveToEmpty", function(data)
    local source = source
    handleWeaponRemoval(data, source)
    print(tostring(data.originSlot))
    print(tostring(data.destinationSlot))
    if data.originOwner == data.destinationOwner and data.originTier.name == data.destinationTier.name then
        local originInvHandler = InvType[data.originTier.name]
        originInvHandler.getInventory(data.originOwner, function(inventory)
            inventory[tostring(data.destinationSlot)] = inventory[tostring(data.originSlot)]
            inventory[tostring(data.originSlot)] = nil
            originInvHandler.saveInventory(data.originOwner, inventory)
            TriggerEvent('disc-inventoryhud:refreshInventory', data.originOwner)
        end)
    else
        local originInvHandler = InvType[data.originTier.name]
        local destinationInvHandler = InvType[data.destinationTier.name]
        if data.originTier.name == 'shop' then
            local player = ESX.GetPlayerFromIdentifier(data.destinationOwner)
            if player.getMoney() >= data.originItem.price * data.originItem.qty then
                player.removeMoney(data.originItem.price * data.originItem.qty)
            else
                TriggerClientEvent('disc-inventoryhud:refreshInventory', source)
                TriggerClientEvent('disc-inventoryhud:refreshInventory', data.target)
                return
            end
        end

help me please help me

**Comment by DiscworldZA** [comment]
Please be more descriptive with the issue, follow the guideline for posting an issue
