### ISSUE TITLE
[BUG] inventoryhud got nil

### ISSUE THREAD

**Issue by Revel1990** [DiscworldZA/gta-resources#159]
i get this error

**To Reproduce**
Login to server

i also installed disc-ambulancejob and disc-death

**Screenshots**
![image](https://user-images.githubusercontent.com/23440918/68514838-2dc1d000-027f-11ea-9e61-998f71cad72d.png)

**Comment by minorpains** [comment]
We also got this. It appears that the inventory is now dependent on the cache, and if the cache gets cleared, really wonky stuff occurs. Additional detailed information:

We updated and restarted resources (base/ammo/inventoryhud) and everything was working fine. After a server restart, this issue appeared. Half of the Inventory Hud is blank (user inventory side) and server live console reported the above error. 

Upon further inspection, the database for disc-inventory on players that logged in ended up being NULL (they including myself, definitely had items). /ensureInv creates a new database entry for the player that has all the items they should have in it, BUT it still registers the above error as it tries to get the first entry (which is still NULL). When a player that tried /ensureInv logs out, the 2nd disc-inventory database entry for them gets NULL'd out as well. 

Players with nothing in their inventory when logging in can see both sides of the inventory, and can use it normally. In disc-inventory there is no database entry for the player until they purchase/spawn in an item. When they log out and back in, everything seems to still work nominally. However, on next server restart, it breaks again.

Players with nothing in their inventory when logging in and then buying an item, then doing a server restart **WITHOUT CACHE BEING CLEARED** still has a working inventory. 

![disc-inventory](https://user-images.githubusercontent.com/8576691/68521196-41137200-0264-11ea-8693-0fff8f7b8b7f.PNG)

![hud](https://user-images.githubusercontent.com/8576691/68521199-453f8f80-0264-11ea-8c04-67c7ea71a219.PNG)

**Comment by mrdigital0** [comment]
Also having this same issue as well

**Comment by calmitup** [comment]
I also have the same issue.

**Comment by Aurimas823** [comment]
Same..... :(

**Comment by PepoDance** [comment]
@DiscworldZA Any news on a solution for this?

**Comment by mamadlooloo** [comment]
Hello
I'm update inventory hud
------------------------------
    local owner = ESX.GetPlayerFromId(source).identifier
    MySQL.Async.fetchAll('DELETE FROM disc_inventory WHERE data = @data AND owner = @owner',{['@data'] = "null",['@owner'] = owner})  -- Tgiann "Null" Fix 
------------------------------
when i disconnect from server, my inventury set to null.
But this code note working and still same problem.

**Comment by Revel1990** [comment]
Disc placed an update yesterday. so update your inventoryhud to the latest version and try again

**Comment by minorpains** [comment]
This occurred with the latest update @Revel1990 . I *just* tried it.

**Comment by minorpains** [comment]
@mamadlooloo @Revel1990  Looks like the fix is simply switch lines 57 and 58 in disc-inventoryhud: server: player.lua. At least it fixed it all for me

**Comment by Revel1990** [comment]
@minorpains thanks for sharing your fix :). does it still work as a fix for you?

**Comment by minorpains** [comment]
@Revel1990 there still appears to be some syncing issues (not as prevalent), and did have 1 report of a null inventory pop up, but otherwise fine.

**Comment by mamadlooloo** [comment]
@minorpains THANKS MAN. MY PROBLEM SOLVED BY YOUR LINE SWITCH.
----------------------------------------
simply switch lines 57 and 58 in disc-inventoryhud: server: player.lua. At least it fixed it all for me.

**Comment by mamadlooloo** [comment]
Hey guys, i think this is work very good. work for me. if you have any problem tell me please.
just replace this functions :


---   ---   --->   disc-inventoryhud/server/inventory.lua
```lua
function saveInventories()
    for type, inventories in pairs(loadedInventories) do
        for identifier, inventory in pairs(inventories) do
        	if inventory ~= nil then --- --- Update
	            if table.length(inventory) > 0 then
	                saveLoadedInventory(identifier, type, inventory)
	            else
	                deleteInventory(identifier, type)
	            end
        	end --- --- Update
        end
    end
    RconPrint('[Inventory] -> [SAVED] -> All Inventories' .. "\n")
end
```
---   ---   ---   ---   ---   ---


---   ---   --->   disc-inventoryhud/server/inventory.lua
```lua
function saveLoadedInventory(identifier, type, data)
	if table.length(data) > 0 then --- --- Update
	    MySQL.Async.execute('UPDATE disc_inventory SET data = @data WHERE owner = @owner AND type = @type', {
	        ['@owner'] = identifier,
	        ['@type'] = type,
	        ['@data'] = json.encode(data)
	    }, function(result)
	        if result == 0 then
	            createInventory(identifier, type, data)
	        end
	        loadedInventories[type][identifier] = nil
	        TriggerEvent('disc-inventoryhud:savedInventory', identifier, type, data)
	    end)
	end --- --- Update
end
```
---   ---   ---   ---   ---   ---


---   ---   --->   disc-inventoryhud/utils.lua
```lua
function table.length(T)
    if T == nil then --- Update
        return 0 --- Update
    end --- Update
    local count = 0
    for _ in pairs(T) do
    	count = count + 1
    end
    return count
end
```

**Comment by Revel1990** [comment]
Thanks @mamadlooloo . did you kept the solution from @minorpains or did you set it back to the orginal? at this moment im testing your solution :)

**Comment by Revel1990** [comment]
The fix doesnt work for me i get alot of errors

**Comment by mamadlooloo** [comment]
@Revel1990 No, i'm not using @minorpains solution.

**Comment by rex2630** [comment]
This was fixed in this commit: https://github.com/DiscworldZA/gta-resources/commit/922e63f531c7a8a7c0472616ee861f34b54ce6f8 . Please close the issue.

**Comment by rex2630** [comment]
This was fixed in newest update. Please update inventoryhud. Thanks for your report :)
