### ISSUE TITLE
[BUG] no text to police (Drugsales)

### ISSUE THREAD

**Issue by Luzox** [DiscworldZA/gta-resources#16]
**Describe the bug**
no text to police (Drugsales), when its gone wrong the mythic notify is working.

and yes i have you **gcphone addon** started. aswell as the **base**.

**Comment by DiscworldZA** [comment]
Is there a error popping up anywhere? Do you have gcphone and my gcphone add on installed?

**Comment by Luzox** [comment]
Yep both installed. no error.

**Comment by DiscworldZA** [comment]
Do you have esx_gcphone_addons installed?

**Comment by Luzox** [comment]
Yes both installed.

**Comment by pietervanlillsi** [comment]
If you text a message to 'police' does that send a message to your officers?

**Comment by DiscworldZA** [comment]
If you text a message to 'police' does that send a message to your officers?

**Comment by Luzox** [comment]
yes it does.

**Comment by DiscworldZA** [comment]
Fixed! Thanks you!
