### ISSUE TITLE
[BUG]/giveitem dosent work with the inventory and no interactions are working like drugruns. It basically doesn't put anything into my inventory only the shops work. 

### ISSUE THREAD

**Issue by tekoa679** [DiscworldZA/gta-resources#163]
]/giveitem dosent work with the inventory and no interactions are working like drugruns. It basically doesn't put anything into my inventory only the shops work.

**Comment by TheBritishBrotherhood** [comment]
I would suggest re-installing, This isnt a bug with the onventory system.

**Comment by rex2630** [comment]
Yeah, it should work and its working for everyone, It must be issue somewhere else. Try looking in to ESX or essentialmode.
