### ISSUE TITLE
disc_inventoryhud weapon attachments [BUG]

### ISSUE THREAD

**Issue by TGIANN** [DiscworldZA/gta-resources#165]
Sorry I'm bad speak English
weapon attachments are disappearing

Video: https://youtu.be/DNR-RGNoa7A

**Comment by mamadlooloo** [comment]
Yes it is.
I'm speak to developer of this script in twitch and he said:
I'm working on weapon components soon.
GOOD LUCK

**Comment by Dazedgenie** [comment]
Weapon attachments are a planned feature of the reworked inventory hud

Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
