### ISSUE TITLE
[BUG] using eatables

### ISSUE THREAD

**Issue by Yozz001** [DiscworldZA/gta-resources#168]
**Describe the bug**
when i try and use a item like bread/water ect it says action invalid?
im using esx_optional needs and status along side disc-hud.

seems to be disc-inventoryhud because if i stop that and start inventoryhud it works fine , then i stop inventoryhud and start disc it lets me eat and drink the water?
and bread ect

here is a small video to show you what i am on about.
https://streamable.com/prr14
https://gyazo.com/2fac124138c348f6538f58d4f6908935

start only disc-inventoryhud
cannot eat or drink

start esx_inventoryhud can eat and drink i can use some other items just not certain ones like bread water ect when esx_inventoryhud isnt started they are setup as usable items via other scripts so that isnt the problem.

using the latest update via github.

**Expected behavior**

**Screenshots**

**Videos**
https://gyazo.com/2fac124138c348f6538f58d4f6908935
https://streamable.com/prr14

**Additional context**

**Comment by warbo201** [comment]
Try removing all your items and also check the user_inventory table and make sure all is on 0.

**Comment by lGodHatesMel** [comment]
do /ensureinv to make sure all items are in your invenotry

**Comment by MrNewb** [comment]
I suggest using citizen wait timers in the portion between animation and removing the item on top of what has been suggested.

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
