### ISSUE TITLE
[BUG] Disc-inventory - Unable to arm a weapon while in a vehicle.

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [DiscworldZA/gta-resources#169]
**Describe the bug**
You cant arm a weapon while in a vehicle.

**Expected behavior**
Ability to use weapons while in your vehicle.

**Comment by mamadlooloo** [comment]
Hello
I have same problem and solve it by changing pullout animation script.
If you using pullout animation:
https://forum.fivem.net/t/release-discontinued-weapon-pull-out-animation-for-civilians/542727
remove line 59 in client side
SetCurrentPedWeapon(ped, GetHashKey("WEAPON_UNARMED"), true)
and change line 62 from
holstered = false
to
holstered = true
GOOD LUCK

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
