### ISSUE TITLE
[BUG]Weapon still in hands after removing from inventory

### ISSUE THREAD

**Issue by PhoenixRP-Github** [DiscworldZA/gta-resources#172]
Removing the weapon from the inventory of a player while he has the weapon out when using ESX-Duty will keep the weapon in the players hands. If the weapon has ammo then it will be able to shoot as well.

**Comment by warbo201** [comment]
Just to add onto this, i use "esx_duty" and by adding the following to the client side it will fix this issue

  --Removes weapons from hands when going off duty!
  local removeWeaponList = {453432689, 1593441988, 584646201, 2578377531, 324215364, 736523883, 4024951519, 3220176749, 2210333304, 2937143193, 2634544996, 2144741730, 487013001} -- https://www.se7ensins.com/forums/threads/weapon-and-explosion-hashes-list.1045035/ weapon's codes
  for i=1, #removeWeaponList do
    if GetCurrentPedWeapon(GetPlayerPed(-1), removeWeaponList[i], false) then
      RemoveWeaponFromPed(GetPlayerPed(-1), removeWeaponList[i])
      end
  end

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
