### ISSUE TITLE
[BUG]Disc-Inventoryhud 

### ISSUE THREAD

**Issue by OwnageGalore** [DiscworldZA/gta-resources#174]
**Describe the bug**

**To Reproduce**
login to server, watch the server window .

**Screenshots**
![Capture](https://user-images.githubusercontent.com/18273796/69012192-1fd81300-0941-11ea-825d-75db77d15f3b.PNG)

**Comment by OwnageGalore** [comment]
Once in the server, i must restart all disc scripts to get them to work

**Comment by JEStudios** [comment]
I get this error as well, I think there is another bug report with this same error

**Comment by JEStudios** [comment]
https://github.com/DiscworldZA/gta-resources/issues/159

**Comment by mamadlooloo** [comment]
Hey guys, i think this is work very good. work for me. if you have any problem tell me please.
just replace this functions :


---   ---   --->   disc-inventoryhud/server/inventory.lua
```lua
function saveInventories()
    for type, inventories in pairs(loadedInventories) do
        for identifier, inventory in pairs(inventories) do
        	if inventory ~= nil then --- --- Update
	            if table.length(inventory) > 0 then
	                saveLoadedInventory(identifier, type, inventory)
	            else
	                deleteInventory(identifier, type)
	            end
        	end --- --- Update
        end
    end
    RconPrint('[Inventory] -> [SAVED] -> All Inventories' .. "\n")
end
```
---   ---   ---   ---   ---   ---


---   ---   --->   disc-inventoryhud/server/inventory.lua
```lua
function saveLoadedInventory(identifier, type, data)
	if table.length(data) > 0 then --- --- Update
	    MySQL.Async.execute('UPDATE disc_inventory SET data = @data WHERE owner = @owner AND type = @type', {
	        ['@owner'] = identifier,
	        ['@type'] = type,
	        ['@data'] = json.encode(data)
	    }, function(result)
	        if result == 0 then
	            createInventory(identifier, type, data)
	        end
	        loadedInventories[type][identifier] = nil
	        TriggerEvent('disc-inventoryhud:savedInventory', identifier, type, data)
	    end)
	end --- --- Update
end
```
---   ---   ---   ---   ---   ---


---   ---   --->   disc-inventoryhud/utils.lua
```lua
function table.length(T)
    if T == nil then --- Update
        return 0 --- Update
    end --- Update
    local count = 0
    for _ in pairs(T) do
    	count = count + 1
    end
    return count
end
```

**Comment by rex2630** [comment]
This was fixed in this commit: https://github.com/DiscworldZA/gta-resources/commit/922e63f531c7a8a7c0472616ee861f34b54ce6f8 . Please close the issue.

**Comment by rex2630** [comment]
Please update the inventory to make it fully working. Im closing this issue. Thanks for reporting :)
