### ISSUE TITLE
[BUG] Can't give items & "Robijntjee payed $20" notification

### ISSUE THREAD

**Issue by Robijntjee** [DiscworldZA/gta-resources#176]
**Describe the bug**
- Can't give people a item, i need to drop it when i want to give it to someone.
- No "Robijntjee payed $20" notification in my screen!

**Expected behavior**
- A working 'give' feature
- A notification when someone gives money

**Screenshots**
(dont have)

**Videos**
(Dont have)
**Additional context**
When i want to give to someone a item, it doenst give it to him, also if i want pay someone is doenst give me a message for "You payed Robijntjee $20!" or something like that, so i dont know when i pay someone or when the player gets it...

**Comment by lGodHatesMel** [comment]
U can add a notication to send to the player for when they receive money. Like this. TriggerEvent('notification, 'you been paid $ '..amount.. ' from '..nameofperson..) That's all u gotta do but don't just copy what I put cuz that's obv not going to work just as is

**Comment by Robijntjee** [comment]
> U can add a notication to send to the player for when they receive money. Like this. TriggerEvent('notification, 'you been paid $ '..amount.. ' from '..nameofperson..) That's all u gotta do but don't just copy what I put cuz that's obv not going to work just as is

Still i cant give items to players ;)

**Comment by lGodHatesMel** [comment]
Down load the newest version it now works
