### ISSUE TITLE
[BUG]: Disc_InventoryHud Errors

### ISSUE THREAD

**Issue by mw-138** [DiscworldZA/gta-resources#178]
The following script errors break the inventory hud script and I am unable to view items in my inventory.

When I load into my server, I get the following error messages:

SCRIPT ERROR: @disc-inventoryhud/server/player.lua:27: bad argument #1 to 'pairs' (table expected, got nil)
> cb (@disc-inventoryhud/server/player.lua:27)
> ref (@disc-inventoryhud/server/inventory.lua:614)
>  (@mysql-async/mysql-async.js:14431)

SCRIPT ERROR: @disc-inventoryhud/server/actions.lua:19: attempt to index a nil value (local 'inventory')
> ref (@disc-inventoryhud/server/actions.lua:19)
> ref (@disc-inventoryhud/server/inventory.lua:614)
>  (@mysql-async/mysql-async.js:14431)

I have tried to fix these errors myself, but I just can't wrap my head around why these are happening. It would be great if someone knew a solution. Thanks.

**Comment by mamadlooloo** [comment]
Hey guys, i think this is work very good. work for me. if you have any problem tell me please.
just replace this functions :


---   ---   --->   disc-inventoryhud/server/inventory.lua
```lua
function saveInventories()
    for type, inventories in pairs(loadedInventories) do
        for identifier, inventory in pairs(inventories) do
        	if inventory ~= nil then --- --- Update
	            if table.length(inventory) > 0 then
	                saveLoadedInventory(identifier, type, inventory)
	            else
	                deleteInventory(identifier, type)
	            end
        	end --- --- Update
        end
    end
    RconPrint('[Inventory] -> [SAVED] -> All Inventories' .. "\n")
end
```
---   ---   ---   ---   ---   ---


---   ---   --->   disc-inventoryhud/server/inventory.lua
```lua
function saveLoadedInventory(identifier, type, data)
	if table.length(data) > 0 then --- --- Update
	    MySQL.Async.execute('UPDATE disc_inventory SET data = @data WHERE owner = @owner AND type = @type', {
	        ['@owner'] = identifier,
	        ['@type'] = type,
	        ['@data'] = json.encode(data)
	    }, function(result)
	        if result == 0 then
	            createInventory(identifier, type, data)
	        end
	        loadedInventories[type][identifier] = nil
	        TriggerEvent('disc-inventoryhud:savedInventory', identifier, type, data)
	    end)
	end --- --- Update
end
```
---   ---   ---   ---   ---   ---


---   ---   --->   disc-inventoryhud/utils.lua
```lua
function table.length(T)
    if T == nil then --- Update
        return 0 --- Update
    end --- Update
    local count = 0
    for _ in pairs(T) do
    	count = count + 1
    end
    return count
end
```

**Comment by rex2630** [comment]
This was fixed in this commit: https://github.com/DiscworldZA/gta-resources/commit/922e63f531c7a8a7c0472616ee861f34b54ce6f8 . Please close the issue.

**Comment by rex2630** [comment]
Please update the inventoryhud to latest version. It should be fixed now. Thanks for reporting :)
