### ISSUE TITLE
*** inventoryhud null BUG ***

### ISSUE THREAD

**Issue by mamadlooloo** [DiscworldZA/gta-resources#179]
Hello
I'm update inventoryhud and some times a player disconnect from server, in database ->
"disc_inventory" table -> "data" of "player" set to null.
Please solve this. this is very bad BUG
THANK YOU SO MUCH @DiscworldZA
![01](https://user-images.githubusercontent.com/40916787/69494477-54177a80-0ed1-11ea-80bb-145861891804.jpg)

**Comment by mamadlooloo** [comment]
Hey guys, i think this is work very good. work for me. if you have any problem tell me please.
just replace this functions :


---   ---   --->   disc-inventoryhud/server/inventory.lua
function saveInventories()
    for type, inventories in pairs(loadedInventories) do
        for identifier, inventory in pairs(inventories) do
        	if inventory ~= nil then --- --- Update
	            if table.length(inventory) > 0 then
	                saveLoadedInventory(identifier, type, inventory)
	            else
	                deleteInventory(identifier, type)
	            end
        	end --- --- Update
        end
    end
    RconPrint('[Inventory] -> [SAVED] -> All Inventories' .. "\n")
end
---   ---   ---   ---   ---   ---


---   ---   --->   disc-inventoryhud/server/inventory.lua
function saveLoadedInventory(identifier, type, data)
	if table.length(data) > 0 then --- --- Update
	    MySQL.Async.execute('UPDATE disc_inventory SET data = @data WHERE owner = @owner AND type = @type', {
	        ['@owner'] = identifier,
	        ['@type'] = type,
	        ['@data'] = json.encode(data)
	    }, function(result)
	        if result == 0 then
	            createInventory(identifier, type, data)
	        end
	        loadedInventories[type][identifier] = nil
	        TriggerEvent('disc-inventoryhud:savedInventory', identifier, type, data)
	    end)
	end --- --- Update
end
---   ---   ---   ---   ---   ---


---   ---   --->   disc-inventoryhud/utils.lua
function table.length(T)
	if T == nil then
		return 0
	end
    local count = 0
    for _ in pairs(T) do
    	count = count + 1
    end
    return count
end
---   ---   ---   ---   ---   ---

**Comment by DiscworldZA** [comment]
@mamadlooloo can you pull request this to the main repo?

**Comment by rex2630** [comment]
This was fixed in this commit: https://github.com/DiscworldZA/gta-resources/commit/922e63f531c7a8a7c0472616ee861f34b54ce6f8 . Please close the issue.

**Comment by rex2630** [comment]
Please update the inventory to make it fully working. Im closing this issue. Thanks for reporting :)
