### ISSUE TITLE
[BUG]: Unable to give item to player

### ISSUE THREAD

**Issue by mw-138** [DiscworldZA/gta-resources#180]
**Describe the bug**
Unable to give an item to the player

**To Reproduce**
- Try giving a valid item and amount to a player using the '/giveitem' command
- Try giving a valid item and amount to a player via 'xPlayer.addInventoryItem' server function

**Expected behavior**
A valid item with a given amount should be added to the player's inventory

**Screenshots**
https://i.imgur.com/ORw4Jg5.png

**Videos**
None

**Additional context**
None

**Comment by rex2630** [comment]
Do u have latest version of inventoryhud?

**Comment by DiscworldZA** [comment]
Fixed
