### ISSUE TITLE
[BUG] Can not GIVE weapons to players

### ISSUE THREAD

**Issue by PhoenixRP-Github** [DiscworldZA/gta-resources#187]
When trying to give a weapon to a player there is an error.

`Attempt to index a nil value <field `originTier`>`

**Comment by 69aZfK12** [comment]
@PhoenixRP-Github are u using the newest update?

**Comment by rex2630** [comment]
Temporary fix
`RegisterServerEvent("disc-inventoryhud:GiveItem")
AddEventHandler("disc-inventoryhud:GiveItem", function(data)
 --   handleWeaponRemoval(data, source)
    TriggerEvent('disc-inventoryhud:notifyImpendingRemoval', data.originItem, data.count, source)
    TriggerEvent('disc-inventoryhud:notifyImpendingAddition', data.originItem, data.count, data.target)
    local targetPlayer = ESX.GetPlayerFromId(data.target)
    targetPlayer.addInventoryItem(data.originItem.id, data.count)
    local sourcePlayer = ESX.GetPlayerFromId(source)
    sourcePlayer.removeInventoryItem(data.originItem.id, data.count)
    TriggerClientEvent('disc-inventoryhud:refreshInventory', source)
    TriggerClientEvent('disc-inventoryhud:refreshInventory', data.target)
end)`

**Comment by PhoenixRP-Github** [comment]
Cheers Rex, will give it a shot

**Comment by rex2630** [comment]
Please update the inventoryhud. It has been fixed in newest update. Thanks for report :)

**Comment by PhoenixRP-Github** [comment]
Yeah, believe it was. Was watching the stream
