### ISSUE TITLE
[Feature] ShowID

### ISSUE THREAD

**Issue by maguhd** [DiscworldZA/gta-resources#19]
**Is your feature request related to a problem? Please describe.**
No.

**ADD FEATURE**
If you could add a button to toggle the IDs and a list of the players online showing only the ID and the steamid +holding a clipboard animation, would be great! Thank you!

**Additional context**
Example: [Photos](https://imgur.com/a/gqeevHe)

**Comment by DiscworldZA** [comment]
Definitely possible. Let me try this. Do you know the animation and lib for the clipboard? Also the clip board entity name?

**Comment by maguhd** [comment]
I'm not sure if these are correct:
```
amb@code_human_wander_clipboard@male@base
base
static
amb@code_human_wander_clipboard@male@idle_a
idle_a
idle_b
world_human_clipboard_lo_res_base

inspecting_med_idle_01_clipboard
```

I found these here: [If im not allowed to post this link I can delete it](https://alexguirre.github.io/animations-list/)

**Comment by DiscworldZA** [comment]
Let me find out which one it is. Want to be able to walk around when you are in this mode?

**Comment by maguhd** [comment]
Walkable would be nice.

**Comment by maguhd** [comment]
Hey! I found the clipboard prop: p_amb_clipboard_01

**Comment by DiscworldZA** [comment]
This has been added to show id
