### ISSUE TITLE
[BUG] Pay will not give the other person any cash.

### ISSUE THREAD

**Issue by PhoenixRP-Github** [DiscworldZA/gta-resources#191]
Version: Latest update

When i enter the amount, select pay then select the player it says i handed over the cash but i don't lose anything and the other player gets nothing.

Was working previously.

**Comment by mamadlooloo** [comment]
Same problem for me.

**Comment by rex2630** [comment]
Please update the inventoryhud. It has been fixed in newest update. Thanks for report :)
