### ISSUE TITLE
*** Sell items ( inventoryhud ) ***

### ISSUE THREAD

**Issue by mamadlooloo** [DiscworldZA/gta-resources#196]
Hello, i think if add some places for sell item very good idea.
For example: right inventory show items which i can sell to second-hand shop with prices.
Thanks

**Comment by Dazedgenie** [comment]
Please head over to the new inventory hud repo and put in a feature request there if this is something you would like to suggest to disc for the redesign.

Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
