### ISSUE TITLE
[BUG] : Unable to receive item

### ISSUE THREAD

**Issue by mw-138** [DiscworldZA/gta-resources#198]
**Describe the bug**
When given a weapon via the server event, the items given are displayed on the screen correctly, but the player does not receive the item. I receive two errors when given an item, one from disc-inventoryhud and one from es_extended.

**To Reproduce**
Use the server event to give player a valid item.

**Expected behavior**
Give a valid item to the player.

**Screenshots**
Disc-InventoryHUD Error - https://i.imgur.com/h6d0jZ3.png
ES_Extended Error - https://i.imgur.com/oysfULN.png

**Videos**
None

**Additional context**
I have the latest version of essentialmode, es_extended, disc-base and disc-inventoryhud.

**Comment by rex2630** [comment]
I dont see any disc inventoryhud error. Did u sent right screens?

**Comment by mw-138** [comment]
I updated the disc-inventoryhud error image

**Comment by rex2630** [comment]
Do u have this in DB? https://github.com/DiscworldZA/gta-resources/blob/master/disc-inventoryhud/sql/disc-inventoryhud.sql#L17

**Comment by rex2630** [comment]
And do u have disc-ammo propertly installed? Maybe that can help

**Comment by mw-138** [comment]
Disc-Ammo is installed properly and yes I do have the SQL in my DB. I'm still getting the same errors.

**Comment by mw-138** [comment]
Turns out I had another server event in another script with the same name and that was conflicting. So now the only problems I'm having are the following:

- disc_inventory table is empty
- disc_inventory_itemdata is empty
- Inventory server error https://i.imgur.com/zCK5kfH.png

I would think the top two errors only occur because the third error occurs.

**Comment by mw-138** [comment]
I missed this error also because the console was printing stuff too fast
https://i.imgur.com/37vXPiF.png

**Comment by rex2630** [comment]
itemdata should be empty, its used to show data of text for each item, so its only optinable. disc_inventory will be empty until you wont get any item to your inventory. And that server error is maybe because u either have nulls in your DB or u just have not existing items in your shop config

**Comment by mw-138** [comment]
Progress has been made. Items show up in the shops, but now the player's inventory is not showing up and I'm receiving this error.
https://i.imgur.com/wtivfZc.png

This error was printed in the console 5 times and there are 5 items in the shop I opened.

**Comment by mw-138** [comment]
I get this error when giving an item to the player.
https://i.imgur.com/uBRs8vh.png

**Comment by mw-138** [comment]
With the latest update of disc-inventoryhud as of writing this, I get this error when trying to give a player a valid item.

Error Screenshot:
https://i.imgur.com/gvYImN8.png

**Comment by mw-138** [comment]
Turns out I just need a fresh reinstall of disc-inventoryhud
