### ISSUE TITLE
[BUG] : Player removed from disc_inventory in database

### ISSUE THREAD

**Issue by mw-138** [DiscworldZA/gta-resources#199]
**Describe the bug**
The player inventory in the disc_inventory table in the database gets turned to null, then can get removed from the table and won't get added automatically. If added manually, it still doesn't work.

**To Reproduce**
I don't know why this happens

**Expected behavior**
Player to be added to disc_inventory table and store the player's inventory

**Screenshots**
https://i.imgur.com/mMluitd.png

**Videos**
None

**Additional context**
None

**Comment by rex2630** [comment]
Do u have latest version? And after updating u need to clear data of disc_inventory table

**Comment by mw-138** [comment]
Yes, I have the latest version. Whenever I receive an error from disc-inventoryhud, the data in disc_inventory table gets cleared.
