### ISSUE TITLE
There is a dupe bug with your armory ![BUG]

### ISSUE THREAD

**Issue by Garbage13** [DiscworldZA/gta-resources#20]
if the armory is opened from 2 guys and they get the weapon the same time they will both get the weapon ! thats a hard bug is it possible to be fixed somehow ?

**Comment by DiscworldZA** [comment]
Yes. I will fix this soon. I understand why this is happening and will make the fix soon. Unfortunately it will still leave a minor racing condition but it should be very minor

**Comment by DiscworldZA** [comment]
Fixed. There are checks in place to forego this issue
