### ISSUE TITLE
[BUG] Shops not functional in new update

### ISSUE THREAD

**Issue by mrdigital0** [DiscworldZA/gta-resources#202]
**Describe the bug**
When going to any of the shops none of the shops have items

**To Reproduce**
visit a shop

**Expected behavior**

**Screenshots**
![20191130200317_1](https://user-images.githubusercontent.com/13575547/69909436-15019180-13c9-11ea-8615-f95776534372.jpg)

**Videos**
If applicable, add videos to help explain your problem.

**Additional context**

**Comment by KeishaTurner** [comment]
I got them working with a workaround

`function formatCurrency(x) {
    x = "" + x;
    return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
}`

**Comment by mrdigital0** [comment]
Where does this go?

**Comment by KeishaTurner** [comment]
into inventory.js line 91

this is just an ugly workaround. you should wait for a fix imho

**Comment by PhoenixRP-Github** [comment]
The fix above is good for temp until Disc sorts it.

**Comment by mrdigital0** [comment]
This did work however it should be noted for When Disc sees this that for Shops the 2nd inventory money part should be hidden? as now it says undefined

**Comment by DiscworldZA** [comment]
The money part is the issue. Shops don't have cash. I can fix this soon

**Comment by mamadlooloo** [comment]
i have same problem
