### ISSUE TITLE
[Feature] vMenu Spawn Item

### ISSUE THREAD

**Issue by Strike5222** [DiscworldZA/gta-resources#203]
**Is your feature request related to a problem? Please describe.**

Whenever I spawn weapons from my vMenu they don't show up in my inventory. (The reason I want to be able to do this is for a easy way of giving weapons in events etc.)

**Describe the solution you'd like**
The solution I'd like to be implemented would just being able to use my menu to spawn said items in, not sure if this is already a thing and I am just having an issue.

**Describe alternatives you've considered**
Another thing would be about the shops, you have to use the built in Disc Shops I'm also curious if their is any way to use esx_shops

**Additional context**

**Comment by 69aZfK12** [comment]
using vMenu gives weapons as a weapon.. this inventory is using weapons an an item so it wont work with vMenu. if u want to give ppl weapons do /giveitem 1 weapon_pistol 1 @Strike5222

**Comment by DiscworldZA** [comment]
Change vMenu to give items not weapons
