### ISSUE TITLE
[BUG] Ammo won't reload at all

### ISSUE THREAD

**Issue by pumpaofficial** [DiscworldZA/gta-resources#205]
Alright,
I tried almost everything.
I tried only esx default stuff as extended, es_plugin etc.. just basic plugins.
I tried to print output from client/main.lua where you are using the ammo it self.
**if weapon ~= nil then** won't print you a shit
If you change it to **if weapon ~= currentWeapon then**, it atleast prints you hash of that gun and let you know, that you Reloaded the weapon or have Max Ammo. **BUT IT WON'T ADD THE NEW AMMO TO THE GUN IT SELF**

This script is just broken af

**Comment by DiscworldZA** [comment]
No one else has reported issues with the script and I have shown on stream that it works 100%. If you have any additional information for me to test with I can help
