### ISSUE TITLE
[BUG] need double items in inventory for use

### ISSUE THREAD

**Issue by SubwooferNL** [DiscworldZA/gta-resources#208]
Hi,
first of all. i like your scripting,
only i have an issue.
i have gcphone and ls-radio and both of them are items for use
if i have 1 phone and 1 radio then i cannot use them
if i put 2 of both in my inventory then i can use them
and i cannot find where the problem is.
maybe you have an idea ?

**Comment by PhoenixRP-Github** [comment]
Im also having issues with items and find that giving the person extra items works

**Comment by pietervanlillsi** [comment]
Check your user_inventory table for negative amounts of items. Unfortunately this is an issue with ESX which i cannot fix

**Comment by DiscworldZA** [comment]
Check your user_inventory table for negative amounts of items. Unfortunately this is an issue with ESX which i cannot fix

**Comment by SubwooferNL** [comment]
is there a possible way to fix it ? becaus i like your inventory hud with trunk and glovebox......

**Comment by DiscworldZA** [comment]
Check the readme for disc inventoryhud for the esx compatibility sql
