### ISSUE TITLE
*** Weapons Ammo Bug ***

### ISSUE THREAD

**Issue by mamadlooloo** [DiscworldZA/gta-resources#215]
Hello
I'm buy WEAPON_SNSPISTOL Pistol to slot 1 from shop and pistol ammo as well.
Now, i'm using ammo for WEAPON_SNSPISTOL , and my WEAPON_SNSPISTOL is full.

NOW -> when i'm push 1 , WEAPON_PISTOL get out from my pocket !!!!!!

**Comment by DiscworldZA** [comment]
Please provide video evidence of this happening
