### ISSUE TITLE
[BUG] Inventory HUD

### ISSUE THREAD

**Issue by BlackZon77** [DiscworldZA/gta-resources#217]
In line 135 in disc-inventoryhud/server/player.lua , there still a limit instead of weight (addToInventory(item, 'player', inventory, esxItem.limit).

just replace esxItem.limit to esxItem.weight

**Comment by rex2630** [comment]
Thanks for letting me know. I will look on to that :)

**Comment by rex2630** [comment]
Does it throw any error? If yes, please send me a screen. Thanks,

**Comment by BlackZon77** [comment]
no, i was just browsing the files to see if i didn't have the item.limit and i found it there

**Comment by rex2630** [comment]
Ok. We will change it if there will be any error or in future update. We should do real weight support soon

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
