### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AltyS-CZ** [DiscworldZA/gta-resources#218]
**Describe the bug**
I have the latest version of disc-inventoryhud and disc-base. Whenever I go into my server and I press my key (which is L-ALT), the HUD shows but nothings there. Even weirder, nothing is in my disc-inventory database. I've refreshed some, restarted server and database, nothing works for the info to show up.

**Screenshots**
1. https://imgur.com/a/jy3Qkuk (DataBase)
2. https://imgur.com/a/IGEsxhh (The HUD in-game)
3.  https://imgur.com/a/RTH8oAQ (EnsureInv Error)
**Extra **
Also, The /ensureInv does not work for me I get an error the error is the third link

**Comment by rex2630** [comment]
First of all. U dont have latest ESX, so thats why ensureinv doeesnt work for you, so its not definitely bug. U can fix that by updating ESX and redoing the DB or use old code: https://github.com/DiscworldZA/gta-resources/commit/9073d331ebf99ef2614df9a4a3818a9f70eef7f4 . And u dont even have the updated SQL imported... So update inventoryhud sql :)
