### ISSUE TITLE
[BUG] : Item stack limited to 100 + Inventory dims to black when an item is moved to another slot

### ISSUE THREAD

**Issue by mw-138** [DiscworldZA/gta-resources#220]
**Describe the bug**

**Bug 1.** Items are limited to 100 even though in my database, the item limit is set to -1 meaning infinite.
**Bug 2.** Whenever an item is moved to another slot, the inventory dims to black for ~half a second.

**To Reproduce**

**Bug 1.** No steps to reproduce
**Bug 2.** Move an item to another slot

**Expected behavior**
I expect items to stack more than 100 and for the inventory to not dim to black when moving an item.

**Screenshots**
Stack sizes : https://i.imgur.com/DeYvn7R.png

**Videos**
None

**Additional context**
I don't know if the dimming to black for moving an item is an intentional feature, if so, is there anyway to disable it.

**Comment by rex2630** [comment]
No. -1 is not infiinite :D

**Comment by mw-138** [comment]
Yeah I realised that after I wrote it but got distracted and didn't edit it. It's 9999 isn't it?

**Comment by DiscworldZA** [comment]
Dim to black and back is intended behaviour. This notifies the user that the inventory is busy being processed by the server.

**Comment by DiscworldZA** [comment]
Also limit is not read from the items table but rather from itemdata table
