### ISSUE TITLE
[BUG] inventoryhud

### ISSUE THREAD

**Issue by Frobski** [DiscworldZA/gta-resources#228]
https://gyazo.com/8f7ff6caa0eeb875e3ff3b3a12012117

Almost everytime a player drops something the second inventory doesn't show up

The only change I've made is the design and change the weight back to limit?

**Comment by rex2630** [comment]
Everything else like closing inv works? Im just making sure u have right name of the script, because if u dont it wont properly work. Next thing that comes to my mind is that someone do have opened drop on your server, so thats why its not visible

**Comment by Frobski** [comment]
Closing the inventory inventory works, but when a player drops something you almost never can watch the second inventory, we tried multiple times

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
