### ISSUE TITLE
*** /steal bad BUG ***

### ISSUE THREAD

**Issue by mamadlooloo** [DiscworldZA/gta-resources#231]
**Hello
I'm steal my friend and set 1 dollar to Inventory UI
and now click on STORE button and get this bug.**

![store](https://user-images.githubusercontent.com/40916787/70361137-c86cf900-1895-11ea-8c47-ccf08f00a64d.jpg)

**and next step i'm click on TAKE button and get another error.**

![take](https://user-images.githubusercontent.com/40916787/70361146-cd31ad00-1895-11ea-919d-77e41aa2ce3f.jpg)

**Comment by lGodHatesMel** [comment]
well post what those lines are as things con be different for someone else

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
