### ISSUE TITLE
[BUG] databse

### ISSUE THREAD

**Issue by Exu9x** [DiscworldZA/gta-resources#234]
Well im trying to add sql file in db and get error.
[SQL]create table if not exists compensation
(
    id bigint unsigned auto_increment,
    compensator text not null,
    receiver text not null,
    reason longtext not null,
    amount int not null,
    constraint id
        unique (id)
);
Affected rows: 0
Time: 0.071s

[SQL]

alter table compensation
    add primary key (id);
[Err] 1280 - Incorrect index name 'id'
 Im using zap-hosting. and tried navicat, heidisql

**Comment by rex2630** [comment]
Just remove
alter table disc_ammo
    add primary key (id);
from DB. Thats all u need to do

**Comment by rex2630** [comment]
This issue is fixed in this PR. It will be soon merged, meanwhile u can use my PR. Thanks for reporting :) Im closing this issue now
