### ISSUE TITLE
[BUG] Marker...

### ISSUE THREAD

**Issue by TGIANN** [DiscworldZA/gta-resources#238]
**GIF:** ![ezgif-6-736418b7a482](https://user-images.githubusercontent.com/54374780/70382887-bca43400-1974-11ea-91d2-0566279c425e.gif)

no money on the drop, but the marker showing

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
