### ISSUE TITLE
[BUG] Players using stash or trunks causing issues for next user 

### ISSUE THREAD

**Issue by PhoenixRP-Github** [DiscworldZA/gta-resources#240]
So i have seen this appearing a bit now.

Someone will use the trunk or a stash and leave, the next person cant see the contents of either untill the person re-enters it and closes it and opens his own inventory. This does not always work nor does it always happens but having to restart base and inventoryhud on a live server causes issues for everything that uses it.

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
