### ISSUE TITLE
[BUG] MDT vehicle search error

### ISSUE THREAD

**Issue by Yozz001** [DiscworldZA/gta-resources#243]
**Describe the bug**
when searching for any vehicle no matter the input in the search bar the outcome is this error in the server console. 

[31m[ERROR] [MySQL] [disc-mdt] An error happens on MySQL for query "SELECT * from owned_vehicles o JOIN users u on u.identifier = o.owner where JSON_EXTRACT(VEHICLE, "$.model") = -2144075702": ER_SP_DOES_NOT_EXIST: FUNCTION zap412038-4.JSON_EXTRACT does not exist[0m
SCRIPT ERROR: @disc-mdt/utils/utils.lua:2: bad argument #1 to 'for iterator' (table expected, got nil)
> combine (@disc-mdt/utils/utils.lua:2)
> ref (@disc-mdt/server/vehicles.lua:9)
> (@mysql-async/mysql-async.js:14431)

**Comment by DiscworldZA** [comment]
Update to latest MySQL Server version 8.0+
