### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kayjewlers12** [DiscworldZA/gta-resources#245]
**Describe the bug**

**To Reproduce**

**Expected behavior**
When i do ensureinv every item in my inventory doubles so exp if i have 20 bandages i will get 40... but before when it was 20 i could use them just fine after i do ensureinv i get action impossible on all my items in my inventory... Not Really sure how to explain the issue but that is what happens... i have no errors for any disc resources.

Thank You 

**Screenshots**

**Videos**
If applicable, add videos to help explain your problem.

**Additional context**

**Comment by mamadlooloo** [comment]
Same for meeee

**Comment by mamadlooloo** [comment]
@DiscworldZA

**Comment by mamadlooloo** [comment]
I'm update disc inventory and my problem solved
@Kayjewlers12 @DiscworldZA

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
