### ISSUE TITLE
[BUG] FIX for ammo bug, reloading doesn't work

### ISSUE THREAD

**Issue by Kevintjuhz** [DiscworldZA/gta-resources#254]
When you try to use the ammo clip no ammo gets loaded into the gun. The fix for this issue is very easy.

In disc-ammo resource in the client/main.lua. On line 29 instead of 

`if currentWeapon == v then`

do this:
`if currentWeapon == GetHashKey(v) then`

It is because the variable currentweapon is a hash key of the weapon, and you were trying to compare it to a string. With the function GetHashKey(v) you will find the weapon hash.

**Comment by DiscworldZA** [comment]
The weapon names are warpped in jenkins precompile tags to convert the weapon name to hash on a compile level. The strings are essentially turned into hash on start.
