### ISSUE TITLE
[BUG] Disc-inventoryhud not working and disc-ammo not working with it

### ISSUE THREAD

**Issue by sgtfrostie** [DiscworldZA/gta-resources#259]
**Describe the bug**
A clear and concise description of what the bug is.in Disc-inventory the pictures will not load and disc-ammo dose not work with the guns to load them

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen.what i expected to happen is when i load the script for the pictures to load and the disc-ammo to work with the loading of guns

**Screenshots**
https://cdn.discordapp.com/attachments/572398090900733963/655377956029333525/Screenshot_1.png

**Videos**
If applicable, add videos to help explain your problem.
https://cdn.discordapp.com/attachments/572398090900733963/655378424264785931/FiveM_2019-12-14_11-57-33_Trim.mp4

**Additional context**

**Comment by rex2630** [comment]
Are u reloading when u ara holding a gun?

**Comment by sgtfrostie** [comment]
i have tired it both ways and did not work

**Comment by ed1zc0** [comment]
I have the same problem. Does anyone know the solution?

**Comment by Dazedgenie** [comment]
For the images you will want to verify everything in your html/images folder as well as double check the _resource file to verify that it is looking in the correct area for the images. Ammo was possibly broken in a recent attempt to fix other issues. Please wait for the revised inventoryhud and put in another issue if ammo is not resolved at that time

Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
