### ISSUE TITLE
[BUG] Inventory not closes

### ISSUE THREAD

**Issue by DonDanGG** [DiscworldZA/gta-resources#261]
**Describe the bug**

**To Reproduce**
1. Go to 'inventory'
2. Click on 'any item and use.'
4. See error inventory never dissapear, i have to open it again and then close for it to visualy dissapear

**Expected behavior**
I expected there to be a config with items that should close inventory after use.

**Screenshots**

**Videos**
If applicable, add videos to help explain your problem.

**Additional context**

**Comment by Dazedgenie** [comment]
This feature was found in the disc_inventory_itemdata table in the SQL. To make an item close inventory on use merely set the closeonuse column to 1. If the item should NOT close the inv set it to 0.

Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
