### ISSUE TITLE
*** Item Slot Positions Not Saved ***

### ISSUE THREAD

**Issue by mamadlooloo** [DiscworldZA/gta-resources#264]
Hello
Why items slot position not saved ??????
I'm put 1 item in slot 20 and after rejoin to server, this item jump to slot 1.
This is very bad, WHY ??? @DiscworldZA @rex2630

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
