### ISSUE TITLE
Error loading script server / main.lua in resource disc_base: 

### ISSUE THREAD

**Issue by gibbs92** [DiscworldZA/gta-resources#265]
I have this problem

Creating script environments for disc_base
Error loading script server / main.lua in resource disc_base: @ disc_base / server / main.lua: 7: attempt to index a nil value (global ‘ESX’)
stack traceback:
@ disc_base / server / main.lua: 7: in main chunk
Failed to load script server / main.lua.

I already tried it myself, but I can’t figure it out

this is the log of the server

https://pastebin.com/Eb9fXJv4

and this is the lua file that it is about

https://pastebin.com/Bb9ys40V

**Comment by DiscworldZA** [comment]
You are starting my base before ESX. Startup ESX then my Base

**Comment by gibbs92** [comment]
ow thank you problem solve
