### ISSUE TITLE
[BUG] [disc-inventoryhud] Removes by item type in inventory not by position

### ISSUE THREAD

**Issue by Asama1** [DiscworldZA/gta-resources#266]
**Describe the bug**
When something is removed from the inventory it is removed as an item type. Say you have 500 fishes in your inventory and you go and sell 10 at a time. You will see that 500 fishes are split in 5 stacks of 100 (as per limit) and upon selling ten, 100 are shown as removed (but are not removed actually, only 10 are). So each stack will then have 90 fishes. On next batch each stack will have 80.
But actually from the inventory items are removed correctly.

**To Reproduce**
1. Give yourself 500 units of an item having limit 100
2. Get units below 100 deducted from your inv
3. See all 5 stacks are updated showing wrong number of items left in the inv

**Expected behavior**
Item should be removed from stacks in stack order (from left to right maybe?)

**Comment by Asama1** [comment]
Resource deprecated

**Comment by DiscworldZA** [comment]
Thnx Asama1. New resource to follow
