### ISSUE TITLE
[BUG] Inventory full

### ISSUE THREAD

**Issue by Jeff9771** [DiscworldZA/gta-resources#267]
I have a problem with picking up items. when I pick up items from work, for example, it forces me to pick up those items even if I don’t have space in my inventory

**To Reproduce**
1. Use any script with is giving item to player
2. even if I have full equipment, I still get the item.

![bug](https://user-images.githubusercontent.com/59057243/71180721-0ba27100-2273-11ea-908a-cbcb0d928daa.png)

**Comment by rex2630** [comment]
Hi. This inventory is deprecated and Disc is already working on new one. So please wait for that. Im closing this for now. Thanks for reporting though :)
