### ISSUE TITLE
[BUG]disc armory global esx problem

### ISSUE THREAD

**Issue by gibbs92** [DiscworldZA/gta-resources#269]
can you help my whit this  https://imgur.com/F2MI1P1 and  es_extended is already on the top https://pastebin.com/BEJR6UAw

**Comment by wolgix** [comment]
Same error :(

**Comment by wolgix** [comment]
Could you please fix? 🥇

**Comment by rex2630** [comment]
I already fixed that in my Locales PR guys, try it
