### ISSUE TITLE
[BUG] Closing and opening inventory is breaking.

### ISSUE THREAD

**Issue by LeviMaker** [DiscworldZA/gta-resources#281]
Everything for the inventory is working fine and was working all fine, items load into the inventory, but as soon as I try to move items over the boxes darken. 2 script errors occur when this happens, in 

 @disc-inventoryhud/server/inventory.lua:7: table index is nil

and

 @disc-inventoryhud/server/inventory.lua:15: table index is nil
![image](https://user-images.githubusercontent.com/59591894/71867101-c5ed0180-30d6-11ea-979f-030e24a63805.png)
![image](https://user-images.githubusercontent.com/59591894/71867106-cab1b580-30d6-11ea-8805-972792e8790f.png)
![image](https://user-images.githubusercontent.com/59591894/71867114-ceddd300-30d6-11ea-929d-76d52fd2a1a9.png)

after this, it doesn't allow me to move or click on any of the boxes. and more of the SCRIPT ERRORS occur, it would be great help if you would be able to help me fix this, im not sure if it is a problem with my Database or what is going on, but some insight would be very helpful.

**Comment by LeviMaker** [comment]
Ive fixed the problem. But Now ive run into another problem. whilst moving items around in the boxes they go a dark grey for about 1 second, this is quite annoying, does anyone have any solutions?

**Comment by DiscworldZA** [comment]
This resource is not supported anymore

**Comment by DiscworldZA** [comment]
There is a new one in development

**Comment by rex2630** [comment]
This resource is deprecated and no further support will be provided.

**Comment by A3GMG** [comment]
> Ive fixed the problem. But Now ive run into another problem. whilst moving items around in the boxes they go a dark grey for about 1 second, this is quite annoying, does anyone have any solutions?

how did you get this bug fixed?
