### ISSUE TITLE
[BUG] Equip weapons

### ISSUE THREAD

**Issue by yagizher** [DiscworldZA/gta-resources#283]
I gave weapon as an item, its cool. But i cant equip the weapon because there is no weapon round and bla bla bla. How to equip gun?

**Comment by ShazyLV** [comment]
Same problem. I can spawn any item from /giveitem , but when try /giveweapon, then not see in inventory and can't take. Any fix? Thanks

**Comment by yagizher** [comment]
Up, press tab and select the weapon. Its not a bug i see

**Comment by yagizher** [comment]
s
