### ISSUE TITLE
[BUG] Dupe Items

### ISSUE THREAD

**Issue by aziznas47** [DiscworldZA/gta-resources#291]
**Describe the bug**

**To Reproduce**
1. Go to '...' Sorry my English is so bad First Go inventory and text to value 5 and come head of 5 text minus (-) and drop it you will drop -5 and you get +5

**Expected behavior**

**Screenshots**

**Videos**
If applicable, add videos to help explain your problem.

**Additional context**

**Comment by aziznas47** [comment]
https://youtu.be/u4bCUElHlcE

**Comment by rex2630** [comment]
This resource is deprecated.
