### ISSUE TITLE
[HELP] Try and make it so you can only have one stack per inventory.

### ISSUE THREAD

**Issue by custardyfingers** [DiscworldZA/gta-resources#292]
**Is your feature request related to a problem? Please describe.**
Players can so many stacks of the same item.

**Describe the solution you'd like**
Try and make it so you can only have one stack per inventory. So the limit is 20 bread. But you can still have 20 bread in each slot. Want to make it so you would only have 20 bread all together. 

**Describe alternatives you've considered**
Implementing the esx weight system.

**Additional context**
![FiveM - TEST SERVER 19_01_2020 13_27_37](https://user-images.githubusercontent.com/55015701/72685484-7b11b780-3ae2-11ea-9995-b9c7e93b3d22.png)

**Comment by rex2630** [comment]
This resource  is deprecated

**Comment by custardyfingers** [comment]
is the new inventory an actual drag and drop resource?

**Comment by rex2630** [comment]
Nope, its not even fully working to be fair

**Comment by custardyfingers** [comment]
I mean, do you have any tips for making it for 1 stack only. I was going to implement esx weight but rather just do limit

**Comment by rex2630** [comment]
I don't really know.
