### ISSUE TITLE
SCRIPT ERROR: @disc-inventoryhud/server/inventory.lua:605: attempt to index a nil value (local 'esxItem')

### ISSUE THREAD

**Issue by alfiansm** [DiscworldZA/gta-resources#309]
please help me, i have error 

SCRIPT ERROR: @disc-inventoryhud/server/inventory.lua:605: attempt to index a nil value (local 'esxItem')
> TriggerServerCallback (@es_extended/server/functions.lua:33)
> handler (@es_extended/server/common.lua:89)

**Comment by rex2630** [comment]
Duplicate. #303
