### ISSUE TITLE
[BUG] disc-property, SCRIPT ERROR, Attempt Index Nil Value (local 'propData')

### ISSUE THREAD

**Issue by Duderocktv** [DiscworldZA/gta-resources#31]
**Describe the bug**
Installed newest version of disc property.
Does not seem to pull data from inventoryhud folder
Cannot visit and/or purchase properties

**To Reproduce**
1. Install disc-base and disc-property
2. Press "E" on the '$' icon to Visit Property (Nothing Happens)
3. Press F8
4. See error:
SCRIPT ERROR: @disc-property/client/property.lua:9: attempt to index a nil value (local 'propData')

**Expected behavior**
Should teleport be inside

**Screenshots**
https://cdn.discordapp.com/attachments/565650949297930263/628407607647797248/unknown.png

**Comment by DiscworldZA** [comment]
This issue is due to the database not being configured properly. I have added a fix to prevent this issue but it is a configuration issue.
