### ISSUE TITLE
SCRIPT ERROR: @disc-inventoryhud/server/inventory.lua:604: attempt to index a nil value (local 'esxItem')

### ISSUE THREAD

**Issue by alfiansm** [DiscworldZA/gta-resources#310]
please help me, i have error 

SCRIPT ERROR: @disc-inventoryhud/server/inventory.lua:604: attempt to index a nil value (local 'esxItem')
> TriggerServerCallback (@es_extended/server/functions.lua:33)
> handler (@es_extended/server/common.lua:89)

would really appreciate it if you find a fix

this is the source code
![Screenshot (67)](https://user-images.githubusercontent.com/61925791/76155897-24f5e380-6125-11ea-87d1-b3ff7dc2ed8c.png)

**Comment by rex2630** [comment]
Duplicate. #303
