### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sgtfrostie** [DiscworldZA/gta-resources#312]
**Describe the bug**
A clear and concise description of what the bug is. I added a gun shop into the disc-inventoryhud
and when i go into the shop i keep getting an error.

**Expected behavior**
A clear and concise description of what you expected to happen. to open the shop and be able to use it like the ones in the shops already

**Screenshots**
If applicable, add screenshots to help explain your [problem.](https://cdn.discordapp.com/attachments/572398090900733963/690530367974932530/Screenshot_1.jpg)

**Videos**
If applicable, add videos to help explain your problem.

**Additional context**

**Comment by rex2630** [comment]
https://github.com/DiscworldZA/gta-resources/issues/290
