### ISSUE TITLE
Error loading script server/main.lua in resource esx_skin: @esx_skin/server/main.lua:59: attempt to call a nil value (field 'RegisterCommand')

### ISSUE THREAD

**Issue by SmokeyRP** [DiscworldZA/gta-resources#317]
C:\FXServer>cd /d C:\FXServer\server-data

C:\FXServer\server-data>C:\FXServer\FXServer.exe +exec server.cfg
Creating script environments for _cfx_internal
Found new resource esx_addonaccount in C:/FXServer\server-data/resources//esx_addonaccount
Found new resource esx_joblisting in C:/FXServer\server-data/resources//esx_joblisting
Found new resource esx_jobs in C:/FXServer\server-data/resources//esx_jobs
Found new resource esx_menu_default in C:/FXServer\server-data/resources//esx_menu_default
Found new resource esx_menu_dialog in C:/FXServer\server-data/resources//esx_menu_dialog
Found new resource esx_menu_list in C:/FXServer\server-data/resources//esx_menu_list
Found new resource esx_skin in C:/FXServer\server-data/resources//esx_skin
Found new resource fivem in C:/FXServer\server-data/resources//fivem
Found new resource fivem-awesome1501 in C:/FXServer\server-data/resources//fivem-awesome1501
Found new resource fivem-map-hipster in C:/FXServer\server-data/resources//fivem-map-hipster
Found new resource fivem-map-skater in C:/FXServer\server-data/resources//fivem-map-skater
Found new resource runcode in C:/FXServer\server-data/resources//runcode
Found new resource skinchanger in C:/FXServer\server-data/resources//skinchanger
Found new resource monitor in C:\FXServer\citizen/system_resources//monitor
Found new resource webadmin in C:\FXServer\citizen/system_resources//webadmin
Found new resource esplugin_mysql in C:/FXServer\server-data/resources//[essentialmode]/esplugin_mysql
Found new resource essentialmode in C:/FXServer\server-data/resources//[essentialmode]/essentialmode
Found new resource es_admin2 in C:/FXServer\server-data/resources//[essentialmode]/es_admin2
Found new resource es_ui in C:/FXServer\server-data/resources//[essentialmode]/es_ui
Found new resource mysql-async in C:/FXServer\server-data/resources//[essentialmode]/mysql-async
Found new resource async in C:/FXServer\server-data/resources//[esx]/async
Found new resource cron in C:/FXServer\server-data/resources//[esx]/cron
Found new resource esx_accessories in C:/FXServer\server-data/resources//[esx]/esx_accessories
Found new resource esx_addoninventory in C:/FXServer\server-data/resources//[esx]/esx_addoninventory
Found new resource esx_addons_gcphone in C:/FXServer\server-data/resources//[esx]/esx_addons_gcphone
Found new resource esx_ambulancejob in C:/FXServer\server-data/resources//[esx]/esx_ambulancejob
Found new resource esx_animations in C:/FXServer\server-data/resources//[esx]/esx_animations
Found new resource esx_atm in C:/FXServer\server-data/resources//[esx]/esx_atm
Found new resource esx_bankerjob in C:/FXServer\server-data/resources//[esx]/esx_bankerjob
Found new resource esx_barbershop in C:/FXServer\server-data/resources//[esx]/esx_barbershop
Found new resource esx_basicneeds in C:/FXServer\server-data/resources//[esx]/esx_basicneeds
Found new resource esx_billing in C:/FXServer\server-data/resources//[esx]/esx_billing
Found new resource esx_boat in C:/FXServer\server-data/resources//[esx]/esx_boat
Found new resource esx_clotheshop in C:/FXServer\server-data/resources//[esx]/esx_clotheshop
Found new resource esx_cruisecontrol in C:/FXServer\server-data/resources//[esx]/esx_cruisecontrol
Found new resource esx_datastore in C:/FXServer\server-data/resources//[esx]/esx_datastore
Found new resource esx_dmvschool in C:/FXServer\server-data/resources//[esx]/esx_dmvschool
Found new resource esx_drugs in C:/FXServer\server-data/resources//[esx]/esx_drugs
Found new resource esx_holdup in C:/FXServer\server-data/resources//[esx]/esx_holdup
Found new resource esx_identity in C:/FXServer\server-data/resources//[esx]/esx_identity
Found new resource esx_license in C:/FXServer\server-data/resources//[esx]/esx_license
Found new resource esx_lscustom in C:/FXServer\server-data/resources//[esx]/esx_lscustom
Found new resource esx_mechanicjob in C:/FXServer\server-data/resources//[esx]/esx_mechanicjob
Found new resource esx_optionalneeds in C:/FXServer\server-data/resources//[esx]/esx_optionalneeds
Found new resource esx_policejob in C:/FXServer\server-data/resources//[esx]/esx_policejob
Found new resource esx_property in C:/FXServer\server-data/resources//[esx]/esx_property
Found new resource esx_rpchat in C:/FXServer\server-data/resources//[esx]/esx_rpchat
Found new resource esx_service in C:/FXServer\server-data/resources//[esx]/esx_service
Found new resource esx_shops in C:/FXServer\server-data/resources//[esx]/esx_shops
Found new resource esx_sit in C:/FXServer\server-data/resources//[esx]/esx_sit
Found new resource esx_society in C:/FXServer\server-data/resources//[esx]/esx_society
Found new resource esx_status in C:/FXServer\server-data/resources//[esx]/esx_status
Found new resource esx_taxijob in C:/FXServer\server-data/resources//[esx]/esx_taxijob
Found new resource esx_vehicleshop in C:/FXServer\server-data/resources//[esx]/esx_vehicleshop
Found new resource esx_voice in C:/FXServer\server-data/resources//[esx]/esx_voice
Found new resource esx_weaponshop in C:/FXServer\server-data/resources//[esx]/esx_weaponshop
Found new resource es_extended in C:/FXServer\server-data/resources//[esx]/es_extended
Found new resource instance in C:/FXServer\server-data/resources//[esx]/instance
Found new resource race in C:/FXServer\server-data/resources//[gamemodes]/race
Found new resource race-test in C:/FXServer\server-data/resources//[gamemodes]/race-test
Found new resource channelfeed in C:/FXServer\server-data/resources//[gameplay]/channelfeed
Found new resource irc in C:/FXServer\server-data/resources//[gameplay]/irc
Found new resource obituary in C:/FXServer\server-data/resources//[gameplay]/obituary
Found new resource obituary-deaths in C:/FXServer\server-data/resources//[gameplay]/obituary-deaths
Found new resource playernames in C:/FXServer\server-data/resources//[gameplay]/playernames
Found new resource mapmanager in C:/FXServer\server-data/resources//[managers]/mapmanager
Found new resource baseevents in C:/FXServer\server-data/resources//[system]/baseevents
Found new resource chat in C:/FXServer\server-data/resources//[system]/chat
Found new resource chat-theme-gtao in C:/FXServer\server-data/resources//[system]/chat-theme-gtao
Found new resource hardcap in C:/FXServer\server-data/resources//[system]/hardcap
Found new resource ■■■■■■■ in C:/FXServer\server-data/resources//[system]/■■■■■■■
Found new resource scoreboard in C:/FXServer\server-data/resources//[system]/scoreboard
Found new resource sessionmanager in C:/FXServer\server-data/resources//[system]/sessionmanager
Found new resource spawnmanager in C:/FXServer\server-data/resources//[system]/spawnmanager
Found new resource betaguns in C:/FXServer\server-data/resources//[test]/betaguns
Found new resource gameInit in C:/FXServer\server-data/resources//[test]/gameInit
Found new resource keks in C:/FXServer\server-data/resources//[test]/keks
Found new resource bob74_ipl in C:/FXServer\server-data/resources//[utility]/bob74_ipl
Found new resource gcphone in C:/FXServer\server-data/resources//[utility]/gcphone
Found new resource loqscript-material_load-loadingscreen in C:/FXServer\server-data/resources//[utility]/loqscript-material_load-loadingscreen
Found new resource sesx_assets in C:/FXServer\server-data/resources//[utility]/sesx_assets
Found new resource webpack in C:/FXServer\server-data/resources//[system]/[builders]/webpack
Found new resource yarn in C:/FXServer\server-data/resources//[system]/[builders]/yarn
Creating script environments for sessionmanager
Started resource sessionmanager
Creating script environments for webadmin
Instantiated instance of script FxWebAdmin.BaseServer.
Instantiated instance of script FxWebAdmin.HttpServer+HttpServerScript.
Started resource webadmin
Creating script environments for monitor
Started resource monitor
Creating script environments for mapmanager
Started resource mapmanager
Creating script environments for chat
Started resource chat
Started resource spawnmanager
Started gametype Freeroam
Started resource fivem
Creating script environments for hardcap
Started resource hardcap
Creating script environments for ■■■■■■■
Started resource ■■■■■■■
Started resource scoreboard
Creating script environments for playernames
Started resource playernames
Creating script environments for essentialmode
Started resource essentialmode
Started resource es_ui
Creating script environments for es_admin2
Started resource es_admin2
Creating script environments for mysql-async
Started resource mysql-async
Creating script environments for esplugin_mysql
Started resource esplugin_mysql
Creating script environments for async
Started resource async
Creating script environments for es_extended
Started resource es_extended
Creating script environments for instance
Started resource instance
Started resource esx_menu_default
Started resource esx_menu_list
Started resource esx_menu_dialog
Started resource esx_voice
Creating script environments for esx_addons_gcphone
Started resource esx_addons_gcphone
Creating script environments for gcphone
Started resource gcphone
Creating script environments for esx_billing
Started resource esx_billing
Creating script environments for cron
Started resource cron
Creating script environments for esx_addonaccount
Started resource esx_addonaccount
Creating script environments for esx_society
Started resource esx_society
Started resource skinchanger
Creating script environments for esx_skin
Error loading script server/main.lua in resource esx_skin: @esx_skin/server/main.lua:59: attempt to call a nil value (field ‘RegisterCommand’)
stack traceback:
@esx_skin/server/main.lua:59: in main chunk
Failed to load script server/main.lua.
Started resource esx_skin
Creating script environments for esx_addoninventory
Started resource esx_addoninventory
Creating script environments for esx_datastore
Started resource esx_datastore
Creating script environments for esx_identity
Started resource esx_identity
Creating script environments for esx_license
Started resource esx_license
Started resource esx_animations
Creating script environments for esx_rpchat
Started resource esx_rpchat
Creating script environments for esx_status
Started resource esx_status
Creating script environments for esx_property
Started resource esx_property
Creating script environments for esx_accessories
Started resource esx_accessories
Creating script environments for esx_service
Started resource esx_service
Creating script environments for esx_bankerjob
==== Registering telephone number banker => bank Customer
Started resource esx_bankerjob
Creating script environments for esx_atm
Started resource esx_atm
Started resource esx_cruisecontrol
Creating script environments for esx_clotheshop
Started resource esx_clotheshop
Creating script environments for esx_vehicleshop
==== Registering telephone number cardealer => Dealer customers
Started resource esx_vehicleshop
Creating script environments for esx_boat
Started resource esx_boat
Creating script environments for esx_basicneeds
Started resource esx_basicneeds
Creating script environments for esx_optionalneeds
Started resource esx_optionalneeds
Creating script environments for esx_jobs
Started resource esx_jobs
Creating script environments for esx_weaponshop
Started resource esx_weaponshop
Creating script environments for esx_lscustom
Started resource esx_lscustom
Creating script environments for esx_joblisting
Started resource esx_joblisting
Creating script environments for esx_shops
Started resource esx_shops
Creating script environments for esx_mechanicjob
==== Registering telephone number mechanic => Mechanic Customer
Started resource esx_mechanicjob
Creating script environments for esx_taxijob
==== Registering telephone number taxi => Taxi Client
Started resource esx_taxijob
Creating script environments for esx_drugs
Started resource esx_drugs
Creating script environments for esx_holdup
Started resource esx_holdup
Creating script environments for esx_sit
Started resource esx_sit
Creating script environments for esx_barbershop
Started resource esx_barbershop
Creating script environments for esx_dmvschool
Started resource esx_dmvschool
Creating script environments for esx_ambulancejob
==== Registering telephone number ambulance => Alert Ambulance
Started resource esx_ambulancejob
Creating script environments for esx_policejob
==== Registering telephone number police => Police alert
Started resource esx_policejob
Stopping resource esx_menu_default
Started resource esx_menu_default
Stopping resource esx_menu_list
Started resource esx_menu_list
Stopping resource esx_menu_dialog
Started resource esx_menu_dialog
Stopping resource esx_skin
Creating script environments for esx_skin
Error loading script server/main.lua in resource esx_skin: @esx_skin/server/main.lua:59: attempt to call a nil value (field ‘RegisterCommand’)
stack traceback:
@esx_skin/server/main.lua:59: in main chunk
Failed to load script server/main.lua.
Started resource esx_skin
Stopping resource skinchanger
Started resource skinchanger
Stopping resource esx_addonaccount
Creating script environments for esx_addonaccount
Started resource esx_addonaccount
Stopping resource esx_jobs
Creating script environments for esx_jobs
Started resource esx_jobs
Stopping resource esx_joblisting
Creating script environments for esx_joblisting
Started resource esx_joblisting
Started resource sesx_assets
Started resource bob74_ipl
Started resource loqscript-material_load-loadingscreen
Stopping resource sessionmanager
Creating script environments for sessionmanager
Started resource sessionmanager
Authenticating server license key…
Server license key authentication succeeded. Welcome!
cfx> Sending heartbeat to https://servers-ingress-live.fivem.net/ingress
Performing version check against: https://api.kanersps.pw/em/version?version=6.3.0&uuid=a10fcdec-d837-4039-4233-cd4c09f2400d

Started map fivem-map-skater
Started resource fivem-map-skater
Authenticating with Nucleus…
server thread hitch warning: timer interval of 1787 milliseconds
[mysql-async] Database server connection established.

[EssentialMode] Current version: 6.3.0
[EssentialMode] Updater version: 6.2.2

[EssentialMode] Everything is nice and updated!

Advertisement: Want to have EssentialMode pre-installed on a good and affordable server host? Go to the following link: https://zap-hosting.com/EssentialMode
fff
cccc ff xx xx rr rr eee
cc ffff xx rrr r ee e
cc ff xx … rr eeeee
ccccc ff xx xx … rr eeeee

Authenticated with cfx.re Nucleus: https://sm0k3y-levdz7.users.cfx.re/
Sending heartbeat to https://servers-ingress-live.fivem.net/ingress
Sending heartbeat to https://servers-ingress-live.fivem.net/ingress
server thread hitch warning: timer interval of 198 milliseconds

This is what is inside my server.cfg

Vanilla
start mapmanager

start chat

start spawnmanager

start sessionmanager

start fivem

start hardcap

start ■■■■■■■

start scoreboard

start playernames

Essentialmode
start essentialmode

start es_ui

start es_admin2

start mysql-async

start esplugin_mysql

ESX
start es_extended

start async

start instance

start esx_menu_default

start esx_menu_list

start esx_menu_dialog

start esx_voice

start esx_addons_gcphone

start gcphone

start esx_billing

start esx_society

start cron

start esx_skin

start skinchanger

start esx_addonaccount

start esx_addoninventory

start esx_datastore

start esx_identity

start esx_license

start esx_animations

start esx_rpchat

start esx_status

start esx_property

start esx_accessories

start esx_service

start esx_bankerjob

start esx_atm

start esx_cruisecontrol

start esx_clotheshop

start esx_boat

start esx_basicneeds

start esx_optionalneeds

start esx_jobs

start esx_weaponshop

start esx_lscustom

start esx_joblisting

start esx_shops

start esx_mechanicjob

start esx_taxijob

start esx_vehicleshop

start esx_drugs

start esx_holdup

start esx_sit

start esx_barbershop

start esx_dmvschool

start esx_ambulancejob

start esx_policejob

ESX REQUIRED MODS
ensure esx_menu_default

ensure esx_menu_list

ensure esx_menu_dialog

ensure esx_skin

ensure skinchanger

ensure esx_addonaccount

ESX JOBS
ensure esx_jobs

ensure esx_joblisting

Utility
start sesx_assets

start bob74_ipl

start loqscript-material_load-loadingscreen

Please help :frowning:

**Comment by rex2630** [comment]
This is not ESX support! I'm closing this issue

**Comment by rex2630** [comment]
There are issues for disc scripts, not ESX  scripts!

**Comment by Spazzyorbit** [comment]
What a cunt
