### ISSUE TITLE
[BUG] disc_InventoryHud sql file note working

### ISSUE THREAD

**Issue by mxnmsky** [DiscworldZA/gta-resources#319]
I am unable to upload the sql file as i get these errors. SQL just wont upload
![image](https://user-images.githubusercontent.com/63572886/79184335-fa4d2800-7e52-11ea-87b3-04786dc35ea6.png)

**Comment by rex2630** [comment]
Thats not issue with SQL, u just dont have perms for writing int to that DB, so change that or contact your provider
