### ISSUE TITLE
[Feature] Panic Button

### ISSUE THREAD

**Issue by Kalbino** [DiscworldZA/gta-resources#33]
Police panic button where if an officer presses a key button it set's off a sound for all police officers and puts a the location on the map from where the officer trigger'd the panic button and also places a waypoint on the map for all the police to attend it quicker so they don't have to go into the map to place the marker auto doe's that when the officer presses the panic button.

**Comment by DiscworldZA** [comment]
Added in 962e5baac94ea250ec0fa30ce1847271a28907ca

**Comment by DiscworldZA** [comment]
use /panic
