### ISSUE TITLE
Inventory Hud Truck Glovebox Compatebel

### ISSUE THREAD

**Issue by La-Cour** [DiscworldZA/gta-resources#330]
Hey mate ... i Just Found your Inventory System AND IM FUCKING LOVEING IT ! .. well my thing is .. i have A lot of other things On the server and I will ask you if  can get a package Were it is only the Shops then The Inventory and then The Trunk on cars and Glovebox? 

is that a thing you got and if you have it can i get it to set up :.. fucking Love Your work man

**Comment by rex2630** [comment]
No, there is no such thing. Next time u can ask on discord, closing this
