### ISSUE TITLE
[BUG] disc-property high latency -> 1.00 MS, making disc-base jump to 0.4-0.5 MS.

### ISSUE THREAD

**Issue by Duderocktv** [DiscworldZA/gta-resources#34]
**Describe the bug**
Hey!

So everything works correctly. I had forgotten to add the actual properties to the DB.
However, it seems disc-property is VERY heavy on the server.
Fluctuates between 0.90 and 1.0 MS, constantly. 
Which in turn makes disc-base go up to 0.40, 0.50 MS. Without disc-property, disc base sits at a comfortable 0.03 ms.

**Screenshots**
High Latency with disc-property enabled.
https://imgur.com/URm20vr

Everything is smooth when shutting property off:
https://imgur.com/XnYz0rk

**Videos**
If applicable, add videos to help explain your problem.

**Additional context**

**Comment by DiscworldZA** [comment]
Ok so 0.5ms for base is not alot. Since it renders and does almost 6 markers right there. But the 1ms on property is worrying me. I will have a look at this. There is no overloading warning? Usually kicks in at 7 to 8ms though

**Comment by Duderocktv** [comment]
No warning at all! It seems to jump up to 1.0 and reset itself to 0.90, and then continuously do this.
I'm not sure if it's due to the persistent 'red markers' on the mini map.
And this is only with 2 properties, I was scared what it would be like with 100+ Properties.

esx_property uses about 0.12 for their property stuff. But its quite bare bones. I have about 200+ properties in that script.

If you manage to figure out what is making it so heavy, I will be using your property script.
I will add roughly 100~ properties and send you a pull request so everyone can enjoy and save time.

It's the least I can do to thank you for your hard work.
Do you have a Patreon? I would like to support you.

**Comment by DiscworldZA** [comment]
Ok ill be jumping on stream in abit and hitting this bug.

Yes i have a patreon: www.patreon.com/DiscworldZA

Thanks for reporting this. Hopefully it's an easy fix

**Comment by DiscworldZA** [comment]
What red markers are you referring to? I don't remember making red onesm

**Comment by Duderocktv** [comment]
They are persistent minimap markers, I'm not sure where in the code they are set but it's definitely from the properties script.

Signed up for your Patreon btw. We could always use an innovative coder on our team here at LoveFist RP, if you're looking to be part of a large community! :)

What is your twitch?

**Comment by DiscworldZA** [comment]
Twitch.tv/DiscworldZA

**Comment by DiscworldZA** [comment]
I have multiplied my property config 50 fold and no increase in ms. I am happy with leaving it around the 0.5ms it is for me. This is in no way alot.
