### ISSUE TITLE
Inventory single weapons not working.

### ISSUE THREAD

**Issue by audrianna7** [DiscworldZA/gta-resources#341]
I am having a bug/issue with weapons not being usable until I have duplicate of the same item. So to be able to use a pistol I need to have two of the same pistol in my inventory otherwise it will not allow me to use the gun. I have no idea how to solve this, I have zero errors in the F8 and everything else works perfect.

I have no idea how to reproduce the problem as I don't know how I got the issue in the first place.

If I only have Pistol x1 it says action impossible, soon as I get 2x of the same pistol it works.

**Comment by rex2630** [comment]
Read description, that scripts is deprecated, closing the issue.
