### ISSUE TITLE
[BUG] disc-property garage

### ISSUE THREAD

**Issue by PrismDX** [DiscworldZA/gta-resources#35]
**Describe the bug**
Able to duplicate vehicle in garage by spamming enter when taking it out. 
**To Reproduce**
1. Store
2. Take out
3. while spamming enter

**Expected behavior**
Not duplicate :) 

**Screenshots**
https://i.imgur.com/DKYSDjj.png

**Comment by DiscworldZA** [comment]
Does the menu not close?

**Comment by PrismDX** [comment]
It does, but i spam E and Enter. i forgot to add while also spamming enter

**Comment by DiscworldZA** [comment]
Sql is async so the timing could be the issue. Wonder if other garages have
this issue. Thinking reversing the event orders wil help
