### ISSUE TITLE
[BUG] disc-property cupboard

### ISSUE THREAD

**Issue by PrismDX** [DiscworldZA/gta-resources#36]
**Describe the bug**
Unable to open property inventory.
**To Reproduce**
Not 100% sure but i think it happend when i dragged Combat pistol back into inventory from (maybe the ammo is causing issues?) The result is that i'm unable to open property inventory because propertyWeapons return nil.

**Screenshots**
https://i.imgur.com/gtCS6eP.png

**DB**
{"item_weapon":[{"name":"WEAPON_FIREEXTINGUISHER","count":2000},{"name":"WEAPON_FIREWORK","count":20},null,{"name":"WEAPON_PROXMINE","count":5},null,null,null,null,null,{"name":"WEAPON_BULLPUPRIFLE","count":0},{"name":"WEAPON_CROWBAR","count":0},null,{"name":"WEAPON_KNUCKLE","count":0},{"name":"WEAPON_POOLCUE","count":0},{"name":"WEAPON_CARBINERIFLE","count":0}],"item_standard":[]}

**Comment by DiscworldZA** [comment]
Send me the json in the database inventory

**Comment by PrismDX** [comment]
Added it in the post.

**Comment by Luzox** [comment]
Cant open it aswell, im using inventoryhud from inventoryhud_shops. do i need to change it somewhere?

**Comment by DiscworldZA** [comment]
Not an issue since we using the new inventory hud
