### ISSUE TITLE
[Feature] vehicle tuner that has persistent changes

### ISSUE THREAD

**Issue by MrNewb** [DiscworldZA/gta-resources#44]
**Is your feature request related to a problem? Please describe.**
current tuner addons do not persistently change handling to garages.

**Describe the solution you'd like**
a tuner similar to https://github.com/VoXzE/xgc-tunerchip but with more customization and persistent changes. possibly using the decor alzar mentioned

**Describe alternatives you've considered**
https://github.com/VoXzE/xgc-tunerchip

**Additional context**

**Comment by DiscworldZA** [comment]
Coming with mythic_phone
