### ISSUE TITLE
Error when trying to open inventory (cupboard)

### ISSUE THREAD

**Issue by JEStudios** [DiscworldZA/gta-resources#53]
![image](https://user-images.githubusercontent.com/6571481/66246622-59cbbd80-e6e3-11e9-9954-0a2353e3ef30.png)

Unable to access property inventory aka the cupboard, also please note the kitchen "Make Food" nothing happens when choosing menu and no config options for this menu that I could locate

**Comment by DiscworldZA** [comment]
Property cupboard is being rewritten to my inventoryhud. Esx_inventoryhud will be removed as a dependency
