### ISSUE TITLE
[BUG] disc-property - SEARCH USERS

### ISSUE THREAD

**Issue by johnnypernik** [DiscworldZA/gta-resources#59]
**Describe the bug**
Hey, there is some problem with finding users to give key for property, my guess is that there could be compatiblity problem of that query with mysql-async 3.x.
Isn't it better to chech close players than searching thme in db? It would be way easier and without any risk of problems.

**To Reproduce**
1. Go to 'kitchen'
2. Click on 'give key to'
3. enter any existing firstname or lastname
4. NO CIVILIAN FOUND

**Expected behavior**
It should find a person.

**Comment by dwiprizzy** [comment]
still no clue to fix it ?

**Comment by DiscworldZA** [comment]
This has been fixed in the new update
