### ISSUE TITLE
[BUG] disc-base according disc-jobbase

### ISSUE THREAD

**Issue by EGUltraTM** [DiscworldZA/gta-resources#6]
**Describe the bug**
Cant buy a vehicle in the jobgarage

**To Reproduce**
Try buy a car

Error:
disc-base/client/main.lua:70
Script error disc-jobcars/client/main.lua:126: bad argument #1 to 'pairs' (table expected, got nil)

**Comment by pietervanlillsi** [comment]
Can you attach you config? As well as what job and grade you attempted this with?

**Comment by DiscworldZA** [comment]
Can you attach your config? As well as what job and grade you attempted this with?

**Comment by EGUltraTM** [comment]
here is the config. 
tried the base stuff with police as job and rank 4

**Comment by DiscworldZA** [comment]
```
        cars = {
            recruit = {
                { name = 'Police', model = 'police', price = 150000 },
            }
        }
```
You only have recruit cars setup here.
I will see if i can handle the missing grades properly if it's not setup

**Comment by DiscworldZA** [comment]
The code now handles missing configuration properly with a7dc8a13c8f8b211e9f1e601a43495a749bb69de
