### ISSUE TITLE
[BUG] Hotwire

### ISSUE THREAD

**Issue by Daryl791** [DiscworldZA/gta-resources#60]
The issue I am having is with hotwire and any jobs spawn vehicles and Koil's Golf Course.  When the vehicle spawns in. It thinks the vehicle is stolen and as soon as they exit it or shut the engine off.  They have to hotwire the vehicle to use it.

Also goes for any vehicle and admin spawns, once exited they have to dv it and respawn it.

**Comment by DiscworldZA** [comment]
I have added an event you can trigger when spawning the vehicles to allow them to turn over
