### ISSUE TITLE
[BUG] can't search for warrants created

### ISSUE THREAD

**Issue by banannapancakes** [DiscworldZA/gta-resources#69]
**Describe the bug**
Once you fill the info required by the form, it show up the notification that has been created, but if u try to look for the warrant, it does not show anything, only show the "no warrants found" notification

PS: on the sql file i modified the default values instead of:
a.- crime_decription i put crime_description  
b.- char_decription   i put char_description

**To Reproduce**
1. Fill the warrant 
2. Create the warrant
3. Warrant creation notification should appear at the top, where mythic notifcation show up by default
![20191013091951_1](https://user-images.githubusercontent.com/56384939/66718842-408ad700-ed9d-11e9-8b04-34aa7fa3fa1c.jpg)
4. If you try to check for warrants created, either with the "search for warrant" or by using the "list of warrant options", even filling up the form with the exact name of the civilian it will not show the warrants, only show the "no warrants found" notification
![20191013092022_1](https://user-images.githubusercontent.com/56384939/66718855-58faf180-ed9d-11e9-94ac-75411814d552.jpg)

**Expected behavior**
A list of warrants created

**Comment by DiscworldZA** [comment]
Have you executed the SQL?
