### ISSUE TITLE
[BUG] jobcars

### ISSUE THREAD

**Issue by EGUltraTM** [DiscworldZA/gta-resources#7]
**Describe the bug**
I insert all job grades in the config as well. when i buy a car it  is spawning. But there is no entry in the jobcars table. So in this case i cant store it and also cant claim it.

**Comment by DiscworldZA** [comment]
This is probably related to the storing code. Can you tell me which vehicle you have used for this process?

**Comment by EGUltraTM** [comment]
yes the standard test car in your config
the "police" car

**Comment by DiscworldZA** [comment]
Can you show my your jobcars table? The layout?

**Comment by EGUltraTM** [comment]
![jobcars_table](https://user-images.githubusercontent.com/31127586/63216873-6e0c2900-c13c-11e9-8236-02cd5ea3c4b1.PNG)

**Comment by DiscworldZA** [comment]
It seems the SQL is missing a column and the save code was referencing the wrong vehicle causing it to not delete the correct vehicle reference, fixing this right now

**Comment by DiscworldZA** [comment]
Closed by a7dc8a13c8f8b211e9f1e601a43495a749bb69de

**Comment by DiscworldZA** [comment]
You will need to re execute the sql for the mod
