### ISSUE TITLE
[BUG] SQL importing error

### ISSUE THREAD

**Issue by Orellius** [DiscworldZA/gta-resources#73]
**Describe the bug**
There is nothing actually to explain, I made a plain and clear database to test these mods of yours, followed your guide what to install and what not, when imported I get an error.

https://prnt.sc/pivgyr

It happens in every script with your **ALTER TABLE**

Ex for script that has this bug (disc-armory) - 
`ALTER TABLE armory
    ADD PRIMARY KEY (id)`

**To Reproduce**
1. Go to 'any of your SQL files'
2. Click on 'Them, import then.'
3. Scroll down to 'Nowhere'

**Expected behavior**
To be worked?

**Screenshots**
https://prnt.sc/pivgyr

**Videos**
N/A

**Additional context**
None

**Comment by DiscworldZA** [comment]
Import the sql file, one statement at a time
