### ISSUE TITLE
[Feature] disc-inventory drop configurable props

### ISSUE THREAD

**Issue by MrNewb** [DiscworldZA/gta-resources#74]
**Is your feature request related to a problem? Please describe.**
not problem related but easier usability

**Describe the solution you'd like**
Would like to see the inventory script handle dropped object props, default to moneybag (configurable) maybe have a table column that is checked for desired prop ie chocolate bar is dropped so the prop for a chocolate that the user finds would be the dropped item.

**Describe alternatives you've considered**
this can be changed in esx itself or maybe essentialmode but not much information on how to do this for multiple items.

**Additional context**
there is a paid script that does this, but thats not the fivem way :)

**Comment by DiscworldZA** [comment]
No
