### ISSUE TITLE
[Feature] Items Information

### ISSUE THREAD

**Issue by J4far** [DiscworldZA/gta-resources#79]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When buying an item you get the information about that item. for an example: When buying an "ID card"  it will assign your first name, last name and DOB as information on the item and it will show the information when you hover on the item

**Describe alternatives you've considered**
NONE.

**Additional context**
NONE.

**Comment by DiscworldZA** [comment]
Doing meta with esx items is close to impossible. I will be attempting to do this soon but for now it's on the back burner

**Comment by J4far** [comment]
is it possible to use disc-base instead of esx so that inventoryhud(or any other disc-scripts) would be flexible and easy to edit?
