### ISSUE TITLE
[BUG] search bug. duplicate items

### ISSUE THREAD

**Issue by Duqino** [DiscworldZA/gta-resources#91]
Moving items from one inv to another and back again the whole time will double the amount the person had with him/her.

[![Screenshot from Gyazo](https://gyazo.com/9e131eae87eecd02eef8557c95d2fc71/raw)](https://gyazo.com/9e131eae87eecd02eef8557c95d2fc71)

**Comment by Duqino** [comment]
Better gif [![Screenshot from Gyazo](https://gyazo.com/4993cd50dc6e1c3e931a0a6a24b083b9/raw)](https://gyazo.com/4993cd50dc6e1c3e931a0a6a24b083b9)

And just after the gif i gave everything to someone and he got 2000 and 2000 water said in my inventory and i was able to give that to him to. So at the end he had 4000 water.

**Comment by rex2630** [comment]
Is this stil working method?

**Comment by rex2630** [comment]
This was fixed. So please update the inventoryhud to latest version. Thanks for your report :)
