### ISSUE TITLE
[BUG] disc-inventoryhud Car Back Glove Box Drop

### ISSUE THREAD

**Issue by ByWolkan** [DiscworldZA/gta-resources#92]
when we open the car baggage and we put the item the first slot seems empty. After that when we put an item the previous item is disappearing. How could we fix that?  same problems drop and Glove Box.
Video Link : https://youtu.be/FsMOJ_A2gXc

**Comment by ByWolkan** [comment]
in short the first item which we put to baggage disappear and doesn't affect the capacity

**Comment by J4far** [comment]
not only glove box even when I drop items the first item disappears but when I add another item it shows up

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
