### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mans-07** [DiscworldZA/gta-resources#93]
https://cdn.discordapp.com/attachments/565582494636965899/634183980022759434/Screenshot_1.png

**Comment by Duqino** [comment]
Did you fix your problem?

**Comment by KungRaseri** [comment]
Yeah these errors are from having items in your config that are not in the items table in your database.  Make sure to match them by their name.

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
