### ISSUE TITLE
[BUG] disc-inventoryhud, 1-5 keys not working and weapons not usable.

### ISSUE THREAD

**Issue by Bakedbastard** [DiscworldZA/gta-resources#94]
**Describe the bug**
So get no errors or anything but when i have a gun in my inventory and ive got it on the 1-5 slots i still cant equip and use a gun.

**Expected behavior**
Considering the non-error part of running the script I thought it was gonna work like a charm.

**Additional context**
Would really appreciate the help mate, been trying to get my head around this but no luck for like 16 hours straight, so now that i cant possible find anything new by looking im asking for help. So please Obi-Wan Kenobi, you're my only hope!

**Comment by Duqino** [comment]
Did you add all the items in to your items database?

Like this -> [![Screenshot from Gyazo](https://gyazo.com/7777894633ec991959b20f36f887e0c7/raw)](https://gyazo.com/7777894633ec991959b20f36f887e0c7)

Keep in mind that you need the disc-ammo to get any ammo at all. You need to add that to in to your items database. All guns are out of ammo when you spawn them.

Ammo -> [![Screenshot from Gyazo](https://gyazo.com/34723bdf01c43c2c75e97dfaaf0cbe28/raw)](https://gyazo.com/34723bdf01c43c2c75e97dfaaf0cbe28)
