### ISSUE TITLE
[BUG] disc-inventoryhud Weapon stays in hand after storage or dropping.

### ISSUE THREAD

**Issue by minorpains** [DiscworldZA/gta-resources#96]
**Describe the bug**
While wielding a weapon, when you drop or store in another inventory (such as a trunk), the weapon stay's wielded. Live console reports "Blocked Removal". Upon picking up the weapon, whether the pistol is still wielded or not, live console reports "Blocked Addition". If player does not have another weapon, the player will continue to wield this weapon forever until he/she runs out of ammo.

**To Reproduce**
1. Buy a weapon from a store and load some ammo in it via disc-ammo items.
2. Wield the weapon.
3. Drop or store the weapon that's wielded.
4. Notice the character still holding the weapon and being able to use it.

**Expected behavior**
It's expected that when storing or dropping a wielded weapon, that the weapon would no longer be wielded afterwards.

**Videos**
https://youtu.be/RyckB7oFwd4

**Comment by DiscworldZA** [comment]
Fixed
