### ISSUE TITLE
[BUG]Disc-InventoryHUD

### ISSUE THREAD

**Issue by nathandu13200** [DiscworldZA/gta-resources#97]
I have all the resources up to date (essentialmode, es_extended ...) but when I connect to the server I have the errors

![erreur](https://user-images.githubusercontent.com/41104633/67036087-41b06100-f11b-11e9-832f-da04eef44187.PNG)
![erreur2](https://user-images.githubusercontent.com/41104633/67036279-9ce25380-f11b-11e9-845b-890e5d8550bf.PNG)

**Comment by nathandu13200** [comment]
I tried to take an old version of es_extended but it does not change anything

**Comment by teryusanru** [comment]
i don't know its bug or what. but if you setup the rewards in your script like 2 item or more for the reward it not appear in your inventory hud and the database. i solve that using /ensureinv but the management of slot is sort by itself. hope you auto sync the database from the default inventory of es_extended. good work for the inventory. thanks

**Comment by Duqino** [comment]
Did you upload the sql to your database?

**Comment by rex2630** [comment]
Please update the inventoryhud. It has been fixed in newest update. Thanks for report :)
