### ISSUE TITLE
Weapon shop Bug[BUG]

### ISSUE THREAD

**Issue by xmrsiret** [DiscworldZA/gta-resources#98]
**Describe the bug**
the weapon shop have bug..

**Videos**
https://www.youtube.com/watch?v=owkEM-K2XJw&feature=youtu.be

**Comment by Duqino** [comment]
Did you update to the latest version? Because i dont have that problem.

Are there any errors in F8 or console?

**Comment by KungRaseri** [comment]
Yeah this might be an old version of the scripts.  Latest version should take money from the player.

**Comment by DiscworldZA** [comment]
Old version of script shown.
